DELETE FROM AM_SUBSCRIPTION ;
DELETE FROM AM_KEY_CONTEXT_MAPPING ;
DELETE FROM AM_APPLICATION ;
DELETE FROM AM_SUBSCRIBER;
DELETE FROM IDENTITY_OAUTH2_ACCESS_TOKEN ;
DELETE FROM IDENTITY_OAUTH_CONSUMER_APPLICATIONS;


ALTER TABLE AM_SUBSCRIBER ALTER COLUMN SUBSCRIBER_ID RESTART WITH 1;
ALTER TABLE AM_APPLICATION ALTER COLUMN APPLICATION_ID RESTART WITH 100;
ALTER TABLE AM_KEY_CONTEXT_MAPPING ALTER COLUMN KEY_CONTEXT_MAPPING_ID RESTART WITH 500;
ALTER TABLE AM_SUBSCRIPTION ALTER COLUMN SUBSCRIPTION_ID RESTART WITH 1000;

INSERT INTO AM_SUBSCRIBER ( USER_ID , TENANT_ID , EMAIL_ADDRESS , DATE_SUBSCRIBED ) VALUES ('SUMEDHA',0,'SUMEDHA@WSO2.COM','2012-03-05 12:10:11');
INSERT INTO AM_SUBSCRIBER ( USER_ID , TENANT_ID , EMAIL_ADDRESS , DATE_SUBSCRIBED ) VALUES ('PRABATH',0,'PRABATH@WSO2.COM','2012-03-05 12:10:11');
INSERT INTO AM_SUBSCRIBER ( USER_ID , TENANT_ID , EMAIL_ADDRESS , DATE_SUBSCRIBED ) VALUES ('THILINA',0,'THILINA@WSO2.COM','2012-03-05 12:10:11');
INSERT INTO AM_SUBSCRIBER ( USER_ID , TENANT_ID , EMAIL_ADDRESS , DATE_SUBSCRIBED ) VALUES ('UDAYANGA',0,'UDAYANGA@WSO2.COM','2012-03-05 12:10:11');


INSERT INTO AM_APPLICATION  (NAME,SUBSCRIBER_ID ) VALUES ('APPLICATION1',1);
INSERT INTO AM_APPLICATION  (NAME,SUBSCRIBER_ID ) VALUES ('APPLICATION2',1);
INSERT INTO AM_APPLICATION  (NAME,SUBSCRIBER_ID ) VALUES ('APPLICATION3',2);
INSERT INTO AM_APPLICATION  (NAME,SUBSCRIBER_ID ) VALUES ('APPLICATION4',2);
INSERT INTO AM_APPLICATION  (NAME,SUBSCRIBER_ID ) VALUES ('APPLICATION5',3);
INSERT INTO AM_APPLICATION  (NAME,SUBSCRIBER_ID ) VALUES ('DeliciousApp',4);




INSERT INTO AM_KEY_CONTEXT_MAPPING ( CONTEXT , VERSION , ACCESS_TOKEN) VALUES ('/context1','v1','SSDCHEJJ-AWUIS-232');

INSERT INTO AM_KEY_CONTEXT_MAPPING ( CONTEXT , VERSION , ACCESS_TOKEN) VALUES ('/deli2','1.0.0','a1b2c3d4');


INSERT INTO AM_SUBSCRIPTION  ( TIER_ID , API_ID , APPLICATION_ID , KEY_CONTEXT_MAPPING_ID , LAST_ACCESSED ) VALUES ('T1','SUMEDHA_API1_V1.0.0',100,500,'2012-03-05 12:10:11');
INSERT INTO AM_SUBSCRIPTION  ( TIER_ID , API_ID , APPLICATION_ID , KEY_CONTEXT_MAPPING_ID , LAST_ACCESSED ) VALUES ('T1','PRABATH_API2_V1.0.0',101,NULL,'2012-03-05 12:10:11');
INSERT INTO AM_SUBSCRIPTION  ( TIER_ID , API_ID , APPLICATION_ID , KEY_CONTEXT_MAPPING_ID , LAST_ACCESSED ) VALUES ('T1','SUMEDHA_API1_V1.0.0',102,NULL,'2012-03-05 12:10:11');
INSERT INTO AM_SUBSCRIPTION  ( TIER_ID , API_ID , APPLICATION_ID , KEY_CONTEXT_MAPPING_ID , LAST_ACCESSED ) VALUES ('T1','ADMIN_API3_V1.0.0',103,NULL,'2012-03-05 12:10:11');
INSERT INTO AM_SUBSCRIPTION  ( TIER_ID , API_ID , APPLICATION_ID , KEY_CONTEXT_MAPPING_ID , LAST_ACCESSED ) VALUES ('T1','PRABATH_API2_V1.0.0',104,NULL,'2012-03-05 12:10:11');
INSERT INTO AM_SUBSCRIPTION  ( TIER_ID , API_ID , APPLICATION_ID , KEY_CONTEXT_MAPPING_ID , LAST_ACCESSED ) VALUES ('T1','DEL_Delicious_1.0.0',105,501,'2012-03-05 12:10:11');


INSERT INTO IDENTITY_OAUTH_CONSUMER_APPLICATIONS ( APP_NAME , CALLBACK_URL , CONSUMER_KEY , CONSUMER_SECRET ,OAUTH_VERSION , TENANT_ID , USERNAME ) VALUES (NULL,NULL,'CON1','MY PEN','2.0',0,'admin');

INSERT INTO IDENTITY_OAUTH2_ACCESS_TOKEN ( ACCESS_TOKEN ,AUTHZ_USER , CONSUMER_KEY , REFRESH_TOKEN ,TIME_CREATED , TOKEN_SCOPE , TOKEN_STATE ,VALIDITY_PERIOD ) VALUES ('a1b2c3d4',NULL,'CON1',NULL,NULL,NULL,'Active',-1);


SELECT * FROM AM_SUBSCRIBER;
SELECT * FROM AM_APPLICATION;
SELECT * FROM AM_KEY_CONTEXT_MAPPING;
SELECT * FROM AM_SUBSCRIPTION;