DROP TABLE IF EXISTS AM_KEY_CONTEXT_MAPPING;
DROP TABLE IF EXISTS AM_SUBSCRIPTION;
DROP TABLE IF EXISTS AM_APPLICATION;
DROP TABLE IF EXISTS AM_SUBSCRIBER;
DROP TABLE IF EXISTS AM_SUBSCRIPTION_KEY_MAPPING;

CREATE TABLE IF NOT EXISTS AM_SUBSCRIBER (
    SUBSCRIBER_ID INTEGER AUTO_INCREMENT,
    USER_ID VARCHAR(50) NOT NULL,
    TENANT_ID INTEGER NOT NULL,
    EMAIL_ADDRESS VARCHAR(256) NULL,
    DATE_SUBSCRIBED TIMESTAMP NOT NULL,
    PRIMARY KEY (SUBSCRIBER_ID),
    UNIQUE (TENANT_ID,USER_ID)
);

CREATE TABLE IF NOT EXISTS AM_APPLICATION (
    APPLICATION_ID INTEGER AUTO_INCREMENT,
    NAME VARCHAR(100),
    SUBSCRIBER_ID INTEGER,
    FOREIGN KEY(SUBSCRIBER_ID) REFERENCES AM_SUBSCRIBER(SUBSCRIBER_ID) ON UPDATE CASCADE ON DELETE RESTRICT,
    PRIMARY KEY(APPLICATION_ID),
    UNIQUE (NAME,SUBSCRIBER_ID)
);

CREATE TABLE IF NOT EXISTS AM_KEY_CONTEXT_MAPPING (
	KEY_CONTEXT_MAPPING_ID INTEGER PRIMARY KEY AUTO_INCREMENT,
	CONTEXT VARCHAR(256),
	VERSION VARCHAR(30),
	ACCESS_TOKEN VARCHAR(512)
);

CREATE TABLE IF NOT EXISTS AM_SUBSCRIPTION (
    SUBSCRIPTION_ID INTEGER AUTO_INCREMENT,
    TIER_ID VARCHAR(50),
    API_ID VARCHAR(256),
    LAST_ACCESSED TIMESTAMP NULL,
    APPLICATION_ID INTEGER,
    FOREIGN KEY(APPLICATION_ID) REFERENCES AM_APPLICATION(APPLICATION_ID) ON UPDATE CASCADE ON DELETE RESTRICT,
    PRIMARY KEY (SUBSCRIPTION_ID)
);

CREATE TABLE IF NOT EXISTS AM_SUBSCRIPTION_KEY_MAPPING (
    SUBSCRIPTION_ID INTEGER,
    KEY_CONTEXT_MAPPING_ID INTEGER,
    KEY_TYPE VARCHAR(512) NOT NULL,
    FOREIGN KEY(SUBSCRIPTION_ID) REFERENCES AM_SUBSCRIPTION(SUBSCRIPTION_ID) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY(KEY_CONTEXT_MAPPING_ID) REFERENCES AM_KEY_CONTEXT_MAPPING(KEY_CONTEXT_MAPPING_ID) ON UPDATE CASCADE ON DELETE RESTRICT,
    PRIMARY KEY(SUBSCRIPTION_ID,KEY_CONTEXT_MAPPING_ID)
);

