CREATE TABLE DEADLINE (id BIGINT NOT NULL, COMPLETION SMALLINT, DEADLINE_DATE TIMESTAMP, ESCALATION_NAME VARCHAR(255), TASK_ID BIGINT, PRIMARY KEY (id));
CREATE TABLE GENERIC_HUMAN_ROLE -- GenericHumanRole
    (GHR_ID BIGINT NOT NULL, type VARCHAR(23), TASK_ID BIGINT, PRIMARY KEY (GHR_ID));
CREATE TABLE HUMANROLE_ORGENTITY (HUMANROLE_ID BIGINT, ORGENTITY_ID BIGINT);
CREATE TABLE MESSAGE (MESSAGE_ID BIGINT NOT NULL, NAME VARCHAR(255), TYPE VARCHAR(255) NOT NULL, TASK_ID BIGINT, PRIMARY KEY (MESSAGE_ID));
CREATE TABLE MESSAGE_PART -- MessagePart
    (MESSAGE_PART_ID BIGINT NOT NULL, MESSAGE_PART_CONTENT CLOB, MESSAGE_PART_NAME VARCHAR(255), MESSAGE_PART_TYPE VARCHAR(255), MESSAGE_MESSAGE_ID BIGINT, KEY0 VARCHAR(255), PRIMARY KEY (MESSAGE_PART_ID));
CREATE TABLE OPENJPA_SEQUENCE_TABLE (ID SMALLINT NOT NULL, SEQUENCE_VALUE BIGINT, PRIMARY KEY (ID));
CREATE TABLE ORG_ENTITY -- OrganizationalEntity
    (ORG_ENTITY_ID BIGINT NOT NULL, ORG_ENTITY_NAME VARCHAR(255), ORG_ENTITY_TYPE VARCHAR(255), PRIMARY KEY (ORG_ENTITY_ID));
CREATE TABLE PRESENTATION_ELEMENT -- PresentationElement
    (id BIGINT NOT NULL, CONTENT VARCHAR(255), XML_LANG VARCHAR(255), PE_TYPE VARCHAR(31), CONTENT_TYPE VARCHAR(255), TASK_ID BIGINT, PRIMARY KEY (id));
CREATE TABLE PRESENTATION_PARAM -- PresentationParameter
    (id BIGINT NOT NULL, NAME VARCHAR(255), type VARCHAR(20), VALUE VARCHAR(255), TASK_ID BIGINT, PRIMARY KEY (id));
CREATE TABLE TASK (id BIGINT NOT NULL, ACTIVATION_TIME TIMESTAMP, CREATED_ON TIMESTAMP, ESCALATED SMALLINT, EXPIRATION_TIME TIMESTAMP, NAME VARCHAR(255) NOT NULL, PRIORITY INTEGER, SKIPABLE SMALLINT, STATUS VARCHAR(255) NOT NULL, STATUS_BEFORE_SUSPENSION VARCHAR(255), TYPE VARCHAR(255) NOT NULL, PRIMARY KEY (id));
CREATE TABLE TASK_ATTACHMENT -- Attachment
    (id BIGINT NOT NULL, ACCESS_TYPE VARCHAR(255), ATTACHED_AT TIMESTAMP, CONTENT_TYPE VARCHAR(255), ATTACHMENT_NAME VARCHAR(255), VALUE VARCHAR(255), ATTACHED_BY BIGINT, TASK_ID BIGINT, PRIMARY KEY (id));
CREATE TABLE TASK_COMMENT -- Comment
    (id BIGINT NOT NULL, COMMENT_TEXT VARCHAR(8192), COMMENTED_ON TIMESTAMP, TASK_ID BIGINT, COMMENTEDBY_ORG_ENTITY_ID BIGINT, PRIMARY KEY (id));
CREATE INDEX I_DEDLINE_TASK ON DEADLINE (TASK_ID);
CREATE INDEX I_GNRC_RL_TASK ON GENERIC_HUMAN_ROLE (TASK_ID);
CREATE INDEX I_HMNRTTY_ELEMENT ON HUMANROLE_ORGENTITY (ORGENTITY_ID);
CREATE INDEX I_HMNRTTY_HUMANROLE_ID ON HUMANROLE_ORGENTITY (HUMANROLE_ID);
CREATE INDEX I_MESSAGE_TASK ON MESSAGE (TASK_ID);
CREATE INDEX I_MSSGPRT_MESSAGE ON MESSAGE_PART (MESSAGE_MESSAGE_ID);
CREATE INDEX I_PRSNMNT_DTYPE ON PRESENTATION_ELEMENT (PE_TYPE);
CREATE INDEX I_PRSNMNT_TASK ON PRESENTATION_ELEMENT (TASK_ID);
CREATE INDEX I_PRSNPRM_TASK ON PRESENTATION_PARAM (TASK_ID);
CREATE INDEX I_TSK_MNT_ATTACHEDBY ON TASK_ATTACHMENT (ATTACHED_BY);
CREATE INDEX I_TSK_MNT_TASK ON TASK_ATTACHMENT (TASK_ID);
CREATE INDEX I_TSK_MNT_COMMENTEDBY ON TASK_COMMENT (COMMENTEDBY_ORG_ENTITY_ID);
CREATE INDEX I_TSK_MNT_TASK1 ON TASK_COMMENT (TASK_ID);
