
CREATE TABLE BAM_BANDWIDTH_STAT_HOUR_FACT (
  BAM_ID INT NOT NULL,
  BAM_SERVER_ID INT NOT NULL,
  BAM_HOUR_ID INT NOT NULL,
  BAM_BANDWIDTH_NAME VARCHAR(512) NOT NULL,
  BAM_INCOMING_BANDWIDTH BIGINT NOT NULL,
  BAM_OUTGOING_BANDWIDTH BIGINT NOT NULL,
  PRIMARY KEY (BAM_ID)
)
/
CREATE SEQUENCE BAM_BANDWIDTH_STAT_HOUR_FACT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE
/
CREATE OR REPLACE TRIGGER BAM_BANDWIDTH_STAT_HOUR_FACT_TRIG
                    BEFORE INSERT
                    ON BAM_BANDWIDTH_STAT_HOUR_FACT
                    REFERENCING NEW AS NEW
                    FOR EACH ROW
                     BEGIN
                       SELECT BAM_BANDWIDTH_STAT_HOUR_FACT_SEQ.nextval INTO :NEW.BAM_ID  FROM dual;
                    END;
/

CREATE TABLE BAM_BANDWIDTH_STAT_DAY_FACT (
  BAM_ID INT NOT NULL,
  BAM_SERVER_ID INT NOT NULL,
  BAM_DAY_ID INT NOT NULL,
  BAM_BANDWIDTH_NAME VARCHAR(512) NOT NULL,
  BAM_INCOMING_BANDWIDTH BIGINT NOT NULL,
  BAM_OUTGOING_BANDWIDTH BIGINT NOT NULL,
  PRIMARY KEY (BAM_ID)
)

/
CREATE SEQUENCE BAM_BANDWIDTH_STAT_DAY_FACT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE
/
CREATE OR REPLACE TRIGGER BAM_BANDWIDTH_STAT_DAY_FACT_TRIG
                    BEFORE INSERT
                    ON BAM_BANDWIDTH_STAT_DAY_FACT
                    REFERENCING NEW AS NEW
                    FOR EACH ROW
                     BEGIN
                       SELECT BAM_BANDWIDTH_STAT_DAY_FACT_SEQ.nextval INTO :NEW.BAM_ID  FROM dual;
                    END;
/
CREATE TABLE  BAM_BANDWIDTH_STAT_MONTH_FACT (
  BAM_ID INT NOT NULL,
  BAM_SERVER_ID INT NOT NULL,
  BAM_MONTH_ID INT NOT NULL,
  BAM_BANDWIDTH_NAME VARCHAR(512) NOT NULL,
  BAM_INCOMING_BANDWIDTH BIGINT NOT NULL,
  BAM_OUTGOING_BANDWIDTH BIGINT NOT NULL,
  PRIMARY KEY (BAM_ID)
)

/
CREATE SEQUENCE BAM_BANDWIDTH_STAT_MONTH_FACT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE
/
CREATE OR REPLACE TRIGGER BAM_BANDWIDTH_STAT_MONTH_FACT_TRIG
                    BEFORE INSERT
                    ON BAM_BANDWIDTH_STAT_MONTH_FACT
                    REFERENCING NEW AS NEW
                    FOR EACH ROW
                     BEGIN
                       SELECT BAM_BANDWIDTH_STAT_MONTH_FACT_SEQ.nextval INTO :NEW.BAM_ID  FROM dual;
                    END;
/

CREATE TABLE BAM_BANDWIDTH_STAT_QTR_FACT (
  BAM_ID INT NOT NULL,
  BAM_SERVER_ID INT NOT NULL,
  BAM_QTR_ID INT NOT NULL,
  BAM_BANDWIDTH_NAME VARCHAR(512) NOT NULL,
  BAM_INCOMING_BANDWIDTH BIGINT NOT NULL,
  BAM_OUTGOING_BANDWIDTH BIGINT NOT NULL,
  PRIMARY KEY (BAM_ID)
)
 
/
CREATE SEQUENCE BAM_BANDWIDTH_STAT_QTR_FACT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE
/
CREATE OR REPLACE TRIGGER BAM_BANDWIDTH_STAT_QTR_FACT_TRIG
                    BEFORE INSERT
                    ON BAM_BANDWIDTH_STAT_QTR_FACT
                    REFERENCING NEW AS NEW
                    FOR EACH ROW
                     BEGIN
                       SELECT BAM_BANDWIDTH_STAT_QTR_FACT_SEQ.nextval INTO :NEW.BAM_ID  FROM dual;
                    END;
/

CREATE TABLE BAM_BANDWIDTH_STAT_YEAR_FACT (
 BAM_ID INT NOT NULL,
  BAM_SERVER_ID INT NOT NULL,
  BAM_YEAR_ID INT NOT NULL,
  BAM_BANDWIDTH_NAME VARCHAR(512) NOT NULL,
  BAM_INCOMING_BANDWIDTH BIGINT NOT NULL,
  BAM_OUTGOING_BANDWIDTH BIGINT NOT NULL,
  PRIMARY KEY (BAM_ID)
)

/
CREATE SEQUENCE BAM_BANDWIDTH_STAT_YEAR_FACT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE
/
CREATE OR REPLACE TRIGGER BAM_BANDWIDTH_STAT_YEAR_FACT_TRIG
                    BEFORE INSERT
                    ON BAM_BANDWIDTH_STAT_YEAR_FACT
                    REFERENCING NEW AS NEW
                    FOR EACH ROW
                     BEGIN
                       SELECT BAM_BANDWIDTH_STAT_YEAR_FACT_SEQ.nextval INTO :NEW.BAM_ID  FROM dual;
                    END;
/

CREATE TABLE BAM_REG_BANDWIDTH_USAGE_DAY_FACT (
  BAM_ID INT NOT NULL,
  BAM_TENANT_ID INT NOT NULL,
  BAM_DAY_ID INT NOT NULL,
  BAM_BANDWIDTH_NAME VARCHAR(512) NOT NULL,
  BAM_REG_BANDWIDTH BIGINT NOT NULL,
  BAM_REG_HISTORY_BANDWIDTH BIGINT NOT NULL,
  PRIMARY KEY (BAM_ID)
)
 
/
CREATE SEQUENCE BAM_REG_BANDWIDTH_USAGE_DAY_FACT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE
/
CREATE OR REPLACE TRIGGER BAM_REG_BANDWIDTH_USAGE_DAY_FACT_TRIG
                    BEFORE INSERT
                    ON BAM_REG_BANDWIDTH_USAGE_DAY_FACT
                    REFERENCING NEW AS NEW
                    FOR EACH ROW
                     BEGIN
                       SELECT BAM_REG_BANDWIDTH_USAGE_DAY_FACT_SEQ.nextval INTO :NEW.BAM_ID  FROM dual;
                    END;
/

CREATE TABLE BAM_REG_BANDWIDTH_USAGE_MONTH_FACT (
  BAM_ID INT NOT NULL,
  BAM_TENANT_ID INT NOT NULL,
  BAM_MONTH_ID INT NOT NULL,
  BAM_BANDWIDTH_NAME VARCHAR(512) NOT NULL,
  BAM_REG_BANDWIDTH BIGINT NOT NULL,
  BAM_REG_HISTORY_BANDWIDTH BIGINT NOT NULL,
  PRIMARY KEY (BAM_ID)
)
/
CREATE SEQUENCE BAM_REG_BANDWIDTH_USAGE_MONTH_FACT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE
/
CREATE OR REPLACE TRIGGER BAM_REG_BANDWIDTH_USAGE_MONTH_FACT_TRIG
                    BEFORE INSERT
                    ON BAM_REG_BANDWIDTH_USAGE_MONTH_FACT
                    REFERENCING NEW AS NEW
                    FOR EACH ROW
                     BEGIN
                       SELECT BAM_REG_BANDWIDTH_USAGE_MONTH_FACT_SEQ.nextval INTO :NEW.BAM_ID  FROM dual;
                    END;
/


ALTER TABLE BAM_BANDWIDTH_STAT_HOUR_FACT
  ADD CONSTRAINT BAM_BANDWIDTH_STAT_HOUR_FACT_IBFK_2 FOREIGN KEY (BAM_HOUR_ID) REFERENCES BAM_HOUR_DIM (BAM_ID)
/
ALTER TABLE BAM_BANDWIDTH_STAT_HOUR_FACT
  ADD CONSTRAINT BAM_BANDWIDTH_STAT_HOUR_FACT_IBFK_1 FOREIGN KEY (BAM_SERVER_ID) REFERENCES BAM_SERVER (BAM_SERVER_ID)
/
ALTER TABLE BAM_BANDWIDTH_STAT_DAY_FACT
  ADD CONSTRAINT BAM_BANDWIDTH_STAT_DAY_FACT_IBFK_2 FOREIGN KEY (BAM_DAY_ID) REFERENCES BAM_DAY_DIM (BAM_ID)
/
ALTER TABLE BAM_BANDWIDTH_STAT_DAY_FACT
  ADD CONSTRAINT BAM_BANDWIDTH_STAT_DAY_FACT_IBFK_1 FOREIGN KEY (BAM_SERVER_ID) REFERENCES BAM_SERVER (BAM_SERVER_ID)
/
ALTER TABLE BAM_BANDWIDTH_STAT_MONTH_FACT
  ADD CONSTRAINT BAM_BANDWIDTH_STAT_MONTH_FACT_IBFK_2 FOREIGN KEY (BAM_MONTH_ID) REFERENCES BAM_MONTH_DIM (BAM_ID)
/
ALTER TABLE BAM_BANDWIDTH_STAT_MONTH_FACT
  ADD CONSTRAINT BAM_BANDWIDTH_STAT_MONTH_FACT_IBFK_1 FOREIGN KEY (BAM_SERVER_ID) REFERENCES BAM_SERVER (BAM_SERVER_ID)
/
ALTER TABLE BAM_BANDWIDTH_STAT_QTR_FACT
  ADD CONSTRAINT BAM_BANDWIDTH_STAT_QTR_FACT_IBFK_2 FOREIGN KEY (BAM_QTR_ID) REFERENCES BAM_QTR_DIM (BAM_ID)
/
ALTER TABLE BAM_BANDWIDTH_STAT_QTR_FACT
  ADD CONSTRAINT BAM_BANDWIDTH_STAT_QTR_FACT_IBFK_1 FOREIGN KEY (BAM_SERVER_ID) REFERENCES BAM_SERVER (BAM_SERVER_ID)
/
 
ALTER TABLE BAM_BANDWIDTH_STAT_YEAR_FACT
  ADD CONSTRAINT BAM_BANDWIDTH_STAT_YEAR_FACT_IBFK_2 FOREIGN KEY (BAM_YEAR_ID) REFERENCES BAM_YEAR_DIM (BAM_ID)
/
ALTER TABLE BAM_BANDWIDTH_STAT_YEAR_FACT
  ADD CONSTRAINT BAM_BANDWIDTH_STAT_YEAR_FACT_IBFK_1 FOREIGN KEY (BAM_SERVER_ID) REFERENCES BAM_SERVER (BAM_SERVER_ID)  
/
ALTER TABLE BAM_REG_BANDWIDTH_USAGE_DAY_FACT
  ADD CONSTRAINT BAM_REG_BANDWIDTH_USAGE_DAY_FACT_IBFK_1 FOREIGN KEY (BAM_DAY_ID) REFERENCES BAM_DAY_DIM (BAM_ID)  
/ 
ALTER TABLE BAM_REG_BANDWIDTH_USAGE_MONTH_FACT
  ADD CONSTRAINT BAM_REG_BANDWIDTH_USAGE_MONTH_FACT_IBFK_1 FOREIGN KEY (BAM_MONTH_ID) REFERENCES BAM_MONTH_DIM (BAM_ID)
/

