--
-- TABLES
--

CREATE TABLE IF NOT EXISTS BAM_BANDWIDTH_STAT_HOUR_FACT (
  BAM_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  BAM_SERVER_ID INT NOT NULL,
  BAM_HOUR_ID INT NOT NULL,
  BAM_BANDWIDTH_NAME VARCHAR(512) NOT NULL,
  BAM_INCOMING_BANDWIDTH_GB INT NOT NULL,
  BAM_INCOMING_BANDWIDTH_MB INT NOT NULL,
  BAM_INCOMING_BANDWIDTH_KB INT NOT NULL,
  BAM_INCOMING_BANDWIDTH_B INT NOT NULL,
  BAM_OUTGOING_BANDWIDTH_GB INT NOT NULL,
  BAM_OUTGOING_BANDWIDTH_MB INT NOT NULL,
  BAM_OUTGOING_BANDWIDTH_KB INT NOT NULL,
  BAM_OUTGOING_BANDWIDTH_B INT NOT NULL
);

 

CREATE TABLE IF NOT EXISTS BAM_BANDWIDTH_STAT_DAY_FACT (
  BAM_ID INT  NOT NULL AUTO_INCREMENT PRIMARY KEY,
  BAM_SERVER_ID INT  NOT NULL,
  BAM_DAY_ID INT  NOT NULL,
  BAM_BANDWIDTH_NAME VARCHAR(512) NOT NULL,
  BAM_INCOMING_BANDWIDTH_GB INT NOT NULL,
  BAM_INCOMING_BANDWIDTH_MB INT NOT NULL,
  BAM_INCOMING_BANDWIDTH_KB INT NOT NULL,
  BAM_INCOMING_BANDWIDTH_B INT NOT NULL,
  BAM_OUTGOING_BANDWIDTH_GB INT NOT NULL,
  BAM_OUTGOING_BANDWIDTH_MB INT NOT NULL,
  BAM_OUTGOING_BANDWIDTH_KB INT NOT NULL,
  BAM_OUTGOING_BANDWIDTH_B INT NOT NULL
);

 

CREATE TABLE IF NOT EXISTS BAM_BANDWIDTH_STAT_MONTH_FACT (
  BAM_ID INT  NOT NULL AUTO_INCREMENT PRIMARY KEY,
  BAM_SERVER_ID INT  NOT NULL,
  BAM_MONTH_ID INT  NOT NULL,
  BAM_BANDWIDTH_NAME VARCHAR(512) NOT NULL,
  BAM_INCOMING_BANDWIDTH_GB INT NOT NULL,
  BAM_INCOMING_BANDWIDTH_MB INT NOT NULL,
  BAM_INCOMING_BANDWIDTH_KB INT NOT NULL,
  BAM_INCOMING_BANDWIDTH_B INT NOT NULL,
  BAM_OUTGOING_BANDWIDTH_GB INT NOT NULL,
  BAM_OUTGOING_BANDWIDTH_MB INT NOT NULL,
  BAM_OUTGOING_BANDWIDTH_KB INT NOT NULL,
  BAM_OUTGOING_BANDWIDTH_B INT NOT NULL

);

  

CREATE TABLE IF NOT EXISTS BAM_BANDWIDTH_STAT_QTR_FACT (
  BAM_ID INT  NOT NULL AUTO_INCREMENT PRIMARY KEY,
  BAM_SERVER_ID INT  NOT NULL,
  BAM_QTR_ID INT  NOT NULL,
  BAM_BANDWIDTH_NAME VARCHAR(512) NOT NULL,
  BAM_INCOMING_BANDWIDTH_GB INT NOT NULL,
  BAM_INCOMING_BANDWIDTH_MB INT NOT NULL,
  BAM_INCOMING_BANDWIDTH_KB INT NOT NULL,
  BAM_INCOMING_BANDWIDTH_B INT NOT NULL,
  BAM_OUTGOING_BANDWIDTH_GB INT NOT NULL,
  BAM_OUTGOING_BANDWIDTH_MB INT NOT NULL,
  BAM_OUTGOING_BANDWIDTH_KB INT NOT NULL,
  BAM_OUTGOING_BANDWIDTH_B INT NOT NULL
);

 

CREATE TABLE IF NOT EXISTS BAM_BANDWIDTH_STAT_YEAR_FACT (
  BAM_ID INT  NOT NULL AUTO_INCREMENT PRIMARY KEY,
  BAM_SERVER_ID INT  NOT NULL,
  BAM_YEAR_ID INT  NOT NULL,
  BAM_BANDWIDTH_NAME VARCHAR(512) NOT NULL,
  BAM_INCOMING_BANDWIDTH_GB INT NOT NULL,
  BAM_INCOMING_BANDWIDTH_MB INT NOT NULL,
  BAM_INCOMING_BANDWIDTH_KB INT NOT NULL,
  BAM_INCOMING_BANDWIDTH_B INT NOT NULL,
  BAM_OUTGOING_BANDWIDTH_GB INT NOT NULL,
  BAM_OUTGOING_BANDWIDTH_MB INT NOT NULL,
  BAM_OUTGOING_BANDWIDTH_KB INT NOT NULL,
  BAM_OUTGOING_BANDWIDTH_B INT NOT NULL
);

  

CREATE TABLE IF NOT EXISTS BAM_REG_BANDWIDTH_USAGE_DAY_FACT (
  BAM_ID INT  NOT NULL AUTO_INCREMENT PRIMARY KEY,
  BAM_TENANT_ID INT  NOT NULL,
  BAM_DAY_ID INT  NOT NULL,
  BAM_BANDWIDTH_NAME VARCHAR(512) NOT NULL,
  BAM_REG_BANDWIDTH_GB INT NOT NULL,
  BAM_REG_BANDWIDTH_MB INT NOT NULL,
  BAM_REG_BANDWIDTH_KB INT NOT NULL,
  BAM_REG_BANDWIDTH_B INT NOT NULL,
  BAM_REG_HISTORY_BANDWIDTH_GB INT NOT NULL,
  BAM_REG_HISTORY_BANDWIDTH_MB INT NOT NULL,
  BAM_REG_HISTORY_BANDWIDTH_KB INT NOT NULL,
  BAM_REG_HISTORY_BANDWIDTH_B INT NOT NULL
);

 

CREATE TABLE IF NOT EXISTS BAM_REG_BANDWIDTH_USAGE_MONTH_FACT (
  BAM_ID INT  NOT NULL AUTO_INCREMENT PRIMARY KEY,
  BAM_TENANT_ID INT  NOT NULL,
  BAM_MONTH_ID INT  NOT NULL,
  BAM_BANDWIDTH_NAME VARCHAR(512) NOT NULL,
  BAM_REG_BANDWIDTH_GB INT NOT NULL,
  BAM_REG_BANDWIDTH_MB INT NOT NULL,
  BAM_REG_BANDWIDTH_KB INT NOT NULL,
  BAM_REG_BANDWIDTH_B INT NOT NULL,
  BAM_REG_HISTORY_BANDWIDTH_GB INT NOT NULL,
  BAM_REG_HISTORY_BANDWIDTH_MB INT NOT NULL,
  BAM_REG_HISTORY_BANDWIDTH_KB INT NOT NULL,
  BAM_REG_HISTORY_BANDWIDTH_B INT NOT NULL
);



CREATE TABLE  IF NOT EXISTS BAM_INSTANCE_USAGE (
  START_TIMESTAMP timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INSTANCE_ID int NOT NULL AUTO_INCREMENT PRIMARY KEY,
  STOP_TIMESTAMP timestamp NOT NULL DEFAULT '2001-01-01 00:00:00',
  IS_RUNNING BOOLEAN,
  SERVER_URL varchar(40) DEFAULT NULL,
  SERVER_NAME varchar(40) DEFAULT NULL
);



-- 
-- CONSTRAINTS
--


ALTER TABLE BAM_BANDWIDTH_STAT_HOUR_FACT
  ADD CONSTRAINT BAM_BANDWIDTH_STAT_HOUR_FACT_IBFK_2 FOREIGN KEY (BAM_HOUR_ID) REFERENCES BAM_HOUR_DIM (BAM_ID);
ALTER TABLE BAM_BANDWIDTH_STAT_HOUR_FACT
  ADD CONSTRAINT BAM_BANDWIDTH_STAT_HOUR_FACT_IBFK_1 FOREIGN KEY (BAM_SERVER_ID) REFERENCES BAM_SERVER (BAM_SERVER_ID);


ALTER TABLE BAM_BANDWIDTH_STAT_DAY_FACT
  ADD CONSTRAINT BAM_BANDWIDTH_STAT_DAY_FACT_IBFK_2 FOREIGN KEY (BAM_DAY_ID) REFERENCES BAM_DAY_DIM (BAM_ID);
ALTER TABLE BAM_BANDWIDTH_STAT_DAY_FACT
  ADD CONSTRAINT BAM_BANDWIDTH_STAT_DAY_FACT_IBFK_1 FOREIGN KEY (BAM_SERVER_ID) REFERENCES BAM_SERVER (BAM_SERVER_ID);

 

ALTER TABLE BAM_BANDWIDTH_STAT_MONTH_FACT
  ADD CONSTRAINT BAM_BANDWIDTH_STAT_MONTH_FACT_IBFK_2 FOREIGN KEY (BAM_MONTH_ID) REFERENCES BAM_MONTH_DIM (BAM_ID);
ALTER TABLE BAM_BANDWIDTH_STAT_MONTH_FACT
  ADD CONSTRAINT BAM_BANDWIDTH_STAT_MONTH_FACT_IBFK_1 FOREIGN KEY (BAM_SERVER_ID) REFERENCES BAM_SERVER (BAM_SERVER_ID);

 

ALTER TABLE BAM_BANDWIDTH_STAT_QTR_FACT
  ADD CONSTRAINT BAM_BANDWIDTH_STAT_QTR_FACT_IBFK_2 FOREIGN KEY (BAM_QTR_ID) REFERENCES BAM_QTR_DIM (BAM_ID);
ALTER TABLE BAM_BANDWIDTH_STAT_QTR_FACT
  ADD CONSTRAINT BAM_BANDWIDTH_STAT_QTR_FACT_IBFK_1 FOREIGN KEY (BAM_SERVER_ID) REFERENCES BAM_SERVER (BAM_SERVER_ID);  

 

ALTER TABLE BAM_BANDWIDTH_STAT_YEAR_FACT
  ADD CONSTRAINT BAM_BANDWIDTH_STAT_YEAR_FACT_IBFK_2 FOREIGN KEY (BAM_YEAR_ID) REFERENCES BAM_YEAR_DIM (BAM_ID);
ALTER TABLE BAM_BANDWIDTH_STAT_YEAR_FACT
  ADD CONSTRAINT BAM_BANDWIDTH_STAT_YEAR_FACT_IBFK_1 FOREIGN KEY (BAM_SERVER_ID) REFERENCES BAM_SERVER (BAM_SERVER_ID);  

  

ALTER TABLE BAM_REG_BANDWIDTH_USAGE_DAY_FACT
  ADD CONSTRAINT BAM_REG_BANDWIDTH_USAGE_DAY_FACT_IBFK_1 FOREIGN KEY (BAM_DAY_ID) REFERENCES BAM_DAY_DIM (BAM_ID);  
  

ALTER TABLE BAM_REG_BANDWIDTH_USAGE_MONTH_FACT
  ADD CONSTRAINT BAM_REG_BANDWIDTH_USAGE_MONTH_FACT_IBFK_1 FOREIGN KEY (BAM_MONTH_ID) REFERENCES BAM_MONTH_DIM (BAM_ID);



COMMIT;

