
IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[BAM_BANDWIDTH_STAT_HOUR_FACT]') AND TYPE IN (N'U'))
CREATE TABLE BAM_BANDWIDTH_STAT_HOUR_FACT (
  BAM_ID INT NOT NULL IDENTITY,
  BAM_SERVER_ID INT NOT NULL,
  BAM_HOUR_ID INT NOT NULL,
  BAM_BANDWIDTH_NAME VARCHAR(512) NOT NULL,
  BAM_INCOMING_BANDWIDTH BIGINT NOT NULL,
  BAM_OUTGOING_BANDWIDTH BIGINT NOT NULL,
  PRIMARY KEY (BAM_ID)
)
 
IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[BAM_BANDWIDTH_STAT_DAY_FACT]') AND TYPE IN (N'U'))
CREATE TABLE BAM_BANDWIDTH_STAT_DAY_FACT (
  BAM_ID INT NOT NULL IDENTITY,
  BAM_SERVER_ID INT NOT NULL,
  BAM_DAY_ID INT NOT NULL,
  BAM_BANDWIDTH_NAME VARCHAR(512) NOT NULL,
  BAM_INCOMING_BANDWIDTH BIGINT NOT NULL,
  BAM_OUTGOING_BANDWIDTH BIGINT NOT NULL,
  PRIMARY KEY (BAM_ID)
)
 
IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[BAM_BANDWIDTH_STAT_MONTH_FACT]') AND TYPE IN (N'U'))
CREATE TABLE  BAM_BANDWIDTH_STAT_MONTH_FACT (
  BAM_ID INT NOT NULL IDENTITY,
  BAM_SERVER_ID INT NOT NULL,
  BAM_MONTH_ID INT NOT NULL,
  BAM_BANDWIDTH_NAME VARCHAR(512) NOT NULL,
  BAM_INCOMING_BANDWIDTH BIGINT NOT NULL,
  BAM_OUTGOING_BANDWIDTH BIGINT NOT NULL,
  PRIMARY KEY (BAM_ID)
)

IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[BAM_BANDWIDTH_STAT_QTR_FACT]') AND TYPE IN (N'U'))
CREATE TABLE BAM_BANDWIDTH_STAT_QTR_FACT (
  BAM_ID INT NOT NULL IDENTITY,
  BAM_SERVER_ID INT NOT NULL,
  BAM_QTR_ID INT NOT NULL,
  BAM_BANDWIDTH_NAME VARCHAR(512) NOT NULL,
  BAM_INCOMING_BANDWIDTH BIGINT NOT NULL,
  BAM_OUTGOING_BANDWIDTH BIGINT NOT NULL,
  PRIMARY KEY (BAM_ID)
)
 
IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[BAM_BANDWIDTH_STAT_YEAR_FACT]') AND TYPE IN (N'U'))
CREATE TABLE BAM_BANDWIDTH_STAT_YEAR_FACT (
  BAM_ID INT NOT NULL IDENTITY,
  BAM_SERVER_ID INT NOT NULL,
  BAM_YEAR_ID INT NOT NULL,
  BAM_BANDWIDTH_NAME VARCHAR(512) NOT NULL,
  BAM_INCOMING_BANDWIDTH BIGINT NOT NULL,
  BAM_OUTGOING_BANDWIDTH BIGINT NOT NULL,
  PRIMARY KEY (BAM_ID)
)

IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[BAM_REG_BANDWIDTH_USAGE_DAY_FACT]') AND TYPE IN (N'U'))
CREATE TABLE BAM_REG_BANDWIDTH_USAGE_DAY_FACT (
  BAM_ID INT NOT NULL IDENTITY,
  BAM_TENANT_ID INT NOT NULL,
  BAM_DAY_ID INT NOT NULL,
  BAM_BANDWIDTH_NAME VARCHAR(512) NOT NULL,
  BAM_REG_BANDWIDTH BIGINT NOT NULL,
  BAM_REG_HISTORY_BANDWIDTH BIGINT NOT NULL,
  PRIMARY KEY (BAM_ID)
)
 
IF NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[BAM_REG_BANDWIDTH_USAGE_MONTH_FACT]') AND TYPE IN (N'U'))
CREATE TABLE BAM_REG_BANDWIDTH_USAGE_MONTH_FACT (
  BAM_ID INT NOT NULL IDENTITY,
  BAM_TENANT_ID INT NOT NULL,
  BAM_MONTH_ID INT NOT NULL,
  BAM_BANDWIDTH_NAME VARCHAR(512) NOT NULL,
  BAM_REG_BANDWIDTH BIGINT NOT NULL,
  BAM_REG_HISTORY_BANDWIDTH BIGINT NOT NULL,
  PRIMARY KEY (BAM_ID)
)

--
-- CONSTRAINTS 
--


IF NOT EXISTS (SELECT * FROM SYS.FOREIGN_KEYS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[BAM_BANDWIDTH_STAT_HOUR_FACT_IBFK_2]') AND PARENT_OBJECT_ID = OBJECT_ID(N'[DBO].[BAM_BANDWIDTH_STAT_HOUR_FACT]'))
ALTER TABLE BAM_BANDWIDTH_STAT_HOUR_FACT
  ADD CONSTRAINT BAM_BANDWIDTH_STAT_HOUR_FACT_IBFK_2 FOREIGN KEY (BAM_HOUR_ID) REFERENCES BAM_HOUR_DIM (BAM_ID);
IF NOT EXISTS (SELECT * FROM SYS.FOREIGN_KEYS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[BAM_BANDWIDTH_STAT_HOUR_FACT_IBFK_1]') AND PARENT_OBJECT_ID = OBJECT_ID(N'[DBO].[BAM_BANDWIDTH_STAT_HOUR_FACT]'))
ALTER TABLE BAM_BANDWIDTH_STAT_HOUR_FACT
  ADD CONSTRAINT BAM_BANDWIDTH_STAT_HOUR_FACT_IBFK_1 FOREIGN KEY (BAM_SERVER_ID) REFERENCES BAM_SERVER (BAM_SERVER_ID);

IF NOT EXISTS (SELECT * FROM SYS.FOREIGN_KEYS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[BAM_BANDWIDTH_STAT_DAY_FACT_IBFK_2]') AND PARENT_OBJECT_ID = OBJECT_ID(N'[DBO].[BAM_BANDWIDTH_STAT_DAY_FACT]'))
ALTER TABLE BAM_BANDWIDTH_STAT_DAY_FACT
  ADD CONSTRAINT BAM_BANDWIDTH_STAT_DAY_FACT_IBFK_2 FOREIGN KEY (BAM_DAY_ID) REFERENCES BAM_DAY_DIM (BAM_ID);
  
IF NOT EXISTS (SELECT * FROM SYS.FOREIGN_KEYS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[BAM_BANDWIDTH_STAT_DAY_FACT_IBFK_1]') AND PARENT_OBJECT_ID = OBJECT_ID(N'[DBO].[BAM_BANDWIDTH_STAT_DAY_FACT]'))
ALTER TABLE BAM_BANDWIDTH_STAT_DAY_FACT
  ADD CONSTRAINT BAM_BANDWIDTH_STAT_DAY_FACT_IBFK_1 FOREIGN KEY (BAM_SERVER_ID) REFERENCES BAM_SERVER (BAM_SERVER_ID);

  
IF NOT EXISTS (SELECT * FROM SYS.FOREIGN_KEYS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[BAM_BANDWIDTH_STAT_MONTH_FACT_IBFK_2]') AND PARENT_OBJECT_ID = OBJECT_ID(N'[DBO].[BAM_BANDWIDTH_STAT_MONTH_FACT]'))
ALTER TABLE BAM_BANDWIDTH_STAT_MONTH_FACT
  ADD CONSTRAINT BAM_BANDWIDTH_STAT_MONTH_FACT_IBFK_2 FOREIGN KEY (BAM_MONTH_ID) REFERENCES BAM_MONTH_DIM (BAM_ID);
IF NOT EXISTS (SELECT * FROM SYS.FOREIGN_KEYS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[BAM_BANDWIDTH_STAT_MONTH_FACT_IBFK_1]') AND PARENT_OBJECT_ID = OBJECT_ID(N'[DBO].[BAM_BANDWIDTH_STAT_MONTH_FACT]'))
ALTER TABLE BAM_BANDWIDTH_STAT_MONTH_FACT
  ADD CONSTRAINT BAM_BANDWIDTH_STAT_MONTH_FACT_IBFK_1 FOREIGN KEY (BAM_SERVER_ID) REFERENCES BAM_SERVER (BAM_SERVER_ID);
 
IF NOT EXISTS (SELECT * FROM SYS.FOREIGN_KEYS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[BAM_BANDWIDTH_STAT_QTR_FACT_IBFK_2]') AND PARENT_OBJECT_ID = OBJECT_ID(N'[DBO].[BAM_BANDWIDTH_STAT_QTR_FACT]'))
ALTER TABLE BAM_BANDWIDTH_STAT_QTR_FACT
  ADD CONSTRAINT BAM_BANDWIDTH_STAT_QTR_FACT_IBFK_2 FOREIGN KEY (BAM_QTR_ID) REFERENCES BAM_QTR_DIM (BAM_ID);
  
  
IF NOT EXISTS (SELECT * FROM SYS.FOREIGN_KEYS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[BAM_BANDWIDTH_STAT_QTR_FACT_IBFK_1]') AND PARENT_OBJECT_ID = OBJECT_ID(N'[DBO].[BAM_BANDWIDTH_STAT_QTR_FACT]'))
ALTER TABLE BAM_BANDWIDTH_STAT_QTR_FACT
  ADD CONSTRAINT BAM_BANDWIDTH_STAT_QTR_FACT_IBFK_1 FOREIGN KEY (BAM_SERVER_ID) REFERENCES BAM_SERVER (BAM_SERVER_ID);  
 
IF NOT EXISTS (SELECT * FROM SYS.FOREIGN_KEYS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[BAM_BANDWIDTH_STAT_YEAR_FACT_IBFK_2]') AND PARENT_OBJECT_ID = OBJECT_ID(N'[DBO].[BAM_BANDWIDTH_STAT_YEAR_FACT]'))
ALTER TABLE BAM_BANDWIDTH_STAT_YEAR_FACT
  ADD CONSTRAINT BAM_BANDWIDTH_STAT_YEAR_FACT_IBFK_2 FOREIGN KEY (BAM_YEAR_ID) REFERENCES BAM_YEAR_DIM (BAM_ID);

IF NOT EXISTS (SELECT * FROM SYS.FOREIGN_KEYS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[BAM_BANDWIDTH_STAT_YEAR_FACT_IBFK_1]') AND PARENT_OBJECT_ID = OBJECT_ID(N'[DBO].[BAM_BANDWIDTH_STAT_YEAR_FACT]'))
ALTER TABLE BAM_BANDWIDTH_STAT_YEAR_FACT
  ADD CONSTRAINT BAM_BANDWIDTH_STAT_YEAR_FACT_IBFK_1 FOREIGN KEY (BAM_SERVER_ID) REFERENCES BAM_SERVER (BAM_SERVER_ID);  
  
IF NOT EXISTS (SELECT * FROM SYS.FOREIGN_KEYS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[BAM_REG_BANDWIDTH_USAGE_DAY_FACT_IBFK_1]') AND PARENT_OBJECT_ID = OBJECT_ID(N'[DBO].[BAM_REG_BANDWIDTH_USAGE_DAY_FACT]'))
ALTER TABLE BAM_REG_BANDWIDTH_USAGE_DAY_FACT
  ADD CONSTRAINT BAM_REG_BANDWIDTH_USAGE_DAY_FACT_IBFK_1 FOREIGN KEY (BAM_DAY_ID) REFERENCES BAM_DAY_DIM (BAM_ID);  

IF NOT EXISTS (SELECT * FROM SYS.FOREIGN_KEYS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[BAM_REG_BANDWIDTH_USAGE_MONTH_FACT_IBFK_1]') AND PARENT_OBJECT_ID = OBJECT_ID(N'[DBO].[BAM_REG_BANDWIDTH_USAGE_MONTH_FACT]'))
ALTER TABLE BAM_REG_BANDWIDTH_USAGE_MONTH_FACT
  ADD CONSTRAINT BAM_REG_BANDWIDTH_USAGE_MONTH_FACT_IBFK_1 FOREIGN KEY (BAM_MONTH_ID) REFERENCES BAM_MONTH_DIM (BAM_ID);


