/**
 * Copyright (c) 2009, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.wso2.carbon.bam.analyzer.service;

public class IndexDTO {

    private String indexName;
    
    private String indexedTable;
    
    private String[] indexedColumns;
    
    private String dataSourceType;
    
    private String granularity;

    private boolean autoGenerated;

    private boolean manuallyIndexed;
    
    private String cron;

    public String getIndexName() {
        return indexName;
    }

    public void setIndexName(String indexName) {
        this.indexName = indexName;
    }

    public String getIndexedTable() {
        return indexedTable;
    }

    public void setIndexedTable(String indexedTable) {
        this.indexedTable = indexedTable;
    }

    public String[] getIndexedColumns() {
        return indexedColumns;
    }

    public void setIndexedColumns(String[] indexedColumns) {
        this.indexedColumns = indexedColumns;
    }

    public String getDataSourceType() {
        return dataSourceType;
    }

    public void setDataSourceType(String dataSourceType) {
        this.dataSourceType = dataSourceType;
    }

    public boolean isAutoGenerated() {
        return autoGenerated;
    }

    public void setAutoGenerated(boolean autoGenerated) {
        this.autoGenerated = autoGenerated;
    }

    public boolean isManuallyIndexed() {
        return manuallyIndexed;
    }

    public void setManuallyIndexed(boolean manuallyIndexed) {
        this.manuallyIndexed = manuallyIndexed;
    }

    public String getCron() {
        return cron;
    }

    public void setCron(String cron) {
        this.cron = cron;
    }

    public String getGranularity() {
        return granularity;
    }

    public void setGranularity(String granularity) {
        this.granularity = granularity;
    }

}
