/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.wso2.carbon.agent.commons.thrift.service;

import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;
import org.apache.thrift.scheme.TupleScheme;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.BitSet;
import java.util.Collections;
import java.util.EnumMap;
import java.util.EnumSet;
import java.util.HashMap;
import java.util.Map;

public class ThriftEventReceiverService {

    public interface Iface {

        public String defineType(String sessionId, String streamDefinition) throws org.wso2.carbon.agent.commons.thrift.exception.ThriftDifferentTypeDefinitionAlreadyDefinedException, org.wso2.carbon.agent.commons.thrift.exception.ThriftMalformedTypeDefinitionException, org.wso2.carbon.agent.commons.thrift.exception.ThriftTypeDefinitionException, org.wso2.carbon.agent.commons.thrift.exception.ThriftSessionExpiredException, org.apache.thrift.TException;

        public void publish(org.wso2.carbon.agent.commons.thrift.data.ThriftEventBundle eventBundle) throws org.wso2.carbon.agent.commons.thrift.exception.ThriftUndefinedEventTypeException, org.wso2.carbon.agent.commons.thrift.exception.ThriftSessionExpiredException, org.apache.thrift.TException;

    }

    public interface AsyncIface {

        public void defineType(String sessionId, String streamDefinition, org.apache.thrift.async.AsyncMethodCallback<AsyncClient.defineType_call> resultHandler) throws org.apache.thrift.TException;

        public void publish(org.wso2.carbon.agent.commons.thrift.data.ThriftEventBundle eventBundle, org.apache.thrift.async.AsyncMethodCallback<AsyncClient.publish_call> resultHandler) throws org.apache.thrift.TException;

    }

    public static class Client extends org.apache.thrift.TServiceClient implements Iface {
        public static class Factory implements org.apache.thrift.TServiceClientFactory<Client> {
            public Factory() {}
            public Client getClient(org.apache.thrift.protocol.TProtocol prot) {
                return new Client(prot);
            }
            public Client getClient(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TProtocol oprot) {
                return new Client(iprot, oprot);
            }
        }

        public Client(org.apache.thrift.protocol.TProtocol prot)
        {
            super(prot, prot);
        }

        public Client(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TProtocol oprot) {
            super(iprot, oprot);
        }

        public String defineType(String sessionId, String streamDefinition) throws org.wso2.carbon.agent.commons.thrift.exception.ThriftDifferentTypeDefinitionAlreadyDefinedException, org.wso2.carbon.agent.commons.thrift.exception.ThriftMalformedTypeDefinitionException, org.wso2.carbon.agent.commons.thrift.exception.ThriftTypeDefinitionException, org.wso2.carbon.agent.commons.thrift.exception.ThriftSessionExpiredException, org.apache.thrift.TException
        {
            send_defineType(sessionId, streamDefinition);
            return recv_defineType();
        }

        public void send_defineType(String sessionId, String streamDefinition) throws org.apache.thrift.TException
        {
            defineType_args args = new defineType_args();
            args.setSessionId(sessionId);
            args.setStreamDefinition(streamDefinition);
            sendBase("defineType", args);
        }

        public String recv_defineType() throws org.wso2.carbon.agent.commons.thrift.exception.ThriftDifferentTypeDefinitionAlreadyDefinedException, org.wso2.carbon.agent.commons.thrift.exception.ThriftMalformedTypeDefinitionException, org.wso2.carbon.agent.commons.thrift.exception.ThriftTypeDefinitionException, org.wso2.carbon.agent.commons.thrift.exception.ThriftSessionExpiredException, org.apache.thrift.TException
        {
            defineType_result result = new defineType_result();
            receiveBase(result, "defineType");
            if (result.isSetSuccess()) {
                return result.success;
            }
            if (result.ade != null) {
                throw result.ade;
            }
            if (result.mtd != null) {
                throw result.mtd;
            }
            if (result.tde != null) {
                throw result.tde;
            }
            if (result.se != null) {
                throw result.se;
            }
            throw new org.apache.thrift.TApplicationException(org.apache.thrift.TApplicationException.MISSING_RESULT, "defineType failed: unknown result");
        }

        public void publish(org.wso2.carbon.agent.commons.thrift.data.ThriftEventBundle eventBundle) throws org.wso2.carbon.agent.commons.thrift.exception.ThriftUndefinedEventTypeException, org.wso2.carbon.agent.commons.thrift.exception.ThriftSessionExpiredException, org.apache.thrift.TException
        {
            send_publish(eventBundle);
            recv_publish();
        }

        public void send_publish(org.wso2.carbon.agent.commons.thrift.data.ThriftEventBundle eventBundle) throws org.apache.thrift.TException
        {
            publish_args args = new publish_args();
            args.setEventBundle(eventBundle);
            sendBase("publish", args);
        }

        public void recv_publish() throws org.wso2.carbon.agent.commons.thrift.exception.ThriftUndefinedEventTypeException, org.wso2.carbon.agent.commons.thrift.exception.ThriftSessionExpiredException, org.apache.thrift.TException
        {
            publish_result result = new publish_result();
            receiveBase(result, "publish");
            if (result.ue != null) {
                throw result.ue;
            }
            if (result.se != null) {
                throw result.se;
            }
            return;
        }

    }
    public static class AsyncClient extends org.apache.thrift.async.TAsyncClient implements AsyncIface {
        public static class Factory implements org.apache.thrift.async.TAsyncClientFactory<AsyncClient> {
            private org.apache.thrift.async.TAsyncClientManager clientManager;
            private org.apache.thrift.protocol.TProtocolFactory protocolFactory;
            public Factory(org.apache.thrift.async.TAsyncClientManager clientManager, org.apache.thrift.protocol.TProtocolFactory protocolFactory) {
                this.clientManager = clientManager;
                this.protocolFactory = protocolFactory;
            }
            public AsyncClient getAsyncClient(org.apache.thrift.transport.TNonblockingTransport transport) {
                return new AsyncClient(protocolFactory, clientManager, transport);
            }
        }

        public AsyncClient(org.apache.thrift.protocol.TProtocolFactory protocolFactory, org.apache.thrift.async.TAsyncClientManager clientManager, org.apache.thrift.transport.TNonblockingTransport transport) {
            super(protocolFactory, clientManager, transport);
        }

        public void defineType(String sessionId, String streamDefinition, org.apache.thrift.async.AsyncMethodCallback<defineType_call> resultHandler) throws org.apache.thrift.TException {
            checkReady();
            defineType_call method_call = new defineType_call(sessionId, streamDefinition, resultHandler, this, ___protocolFactory, ___transport);
            this.___currentMethod = method_call;
            ___manager.call(method_call);
        }

        public static class defineType_call extends org.apache.thrift.async.TAsyncMethodCall {
            private String sessionId;
            private String streamDefinition;
            public defineType_call(String sessionId, String streamDefinition, org.apache.thrift.async.AsyncMethodCallback<defineType_call> resultHandler, org.apache.thrift.async.TAsyncClient client, org.apache.thrift.protocol.TProtocolFactory protocolFactory, org.apache.thrift.transport.TNonblockingTransport transport) throws org.apache.thrift.TException {
                super(client, protocolFactory, transport, resultHandler, false);
                this.sessionId = sessionId;
                this.streamDefinition = streamDefinition;
            }

            public void write_args(org.apache.thrift.protocol.TProtocol prot) throws org.apache.thrift.TException {
                prot.writeMessageBegin(new org.apache.thrift.protocol.TMessage("defineType", org.apache.thrift.protocol.TMessageType.CALL, 0));
                defineType_args args = new defineType_args();
                args.setSessionId(sessionId);
                args.setStreamDefinition(streamDefinition);
                args.write(prot);
                prot.writeMessageEnd();
            }

            public String getResult() throws org.wso2.carbon.agent.commons.thrift.exception.ThriftDifferentTypeDefinitionAlreadyDefinedException, org.wso2.carbon.agent.commons.thrift.exception.ThriftMalformedTypeDefinitionException, org.wso2.carbon.agent.commons.thrift.exception.ThriftTypeDefinitionException, org.wso2.carbon.agent.commons.thrift.exception.ThriftSessionExpiredException, org.apache.thrift.TException {
                if (getState() != org.apache.thrift.async.TAsyncMethodCall.State.RESPONSE_READ) {
                    throw new IllegalStateException("Method call not finished!");
                }
                org.apache.thrift.transport.TMemoryInputTransport memoryTransport = new org.apache.thrift.transport.TMemoryInputTransport(getFrameBuffer().array());
                org.apache.thrift.protocol.TProtocol prot = client.getProtocolFactory().getProtocol(memoryTransport);
                return (new Client(prot)).recv_defineType();
            }
        }

        public void publish(org.wso2.carbon.agent.commons.thrift.data.ThriftEventBundle eventBundle, org.apache.thrift.async.AsyncMethodCallback<publish_call> resultHandler) throws org.apache.thrift.TException {
            checkReady();
            publish_call method_call = new publish_call(eventBundle, resultHandler, this, ___protocolFactory, ___transport);
            this.___currentMethod = method_call;
            ___manager.call(method_call);
        }

        public static class publish_call extends org.apache.thrift.async.TAsyncMethodCall {
            private org.wso2.carbon.agent.commons.thrift.data.ThriftEventBundle eventBundle;
            public publish_call(org.wso2.carbon.agent.commons.thrift.data.ThriftEventBundle eventBundle, org.apache.thrift.async.AsyncMethodCallback<publish_call> resultHandler, org.apache.thrift.async.TAsyncClient client, org.apache.thrift.protocol.TProtocolFactory protocolFactory, org.apache.thrift.transport.TNonblockingTransport transport) throws org.apache.thrift.TException {
                super(client, protocolFactory, transport, resultHandler, false);
                this.eventBundle = eventBundle;
            }

            public void write_args(org.apache.thrift.protocol.TProtocol prot) throws org.apache.thrift.TException {
                prot.writeMessageBegin(new org.apache.thrift.protocol.TMessage("publish", org.apache.thrift.protocol.TMessageType.CALL, 0));
                publish_args args = new publish_args();
                args.setEventBundle(eventBundle);
                args.write(prot);
                prot.writeMessageEnd();
            }

            public void getResult() throws org.wso2.carbon.agent.commons.thrift.exception.ThriftUndefinedEventTypeException, org.wso2.carbon.agent.commons.thrift.exception.ThriftSessionExpiredException, org.apache.thrift.TException {
                if (getState() != org.apache.thrift.async.TAsyncMethodCall.State.RESPONSE_READ) {
                    throw new IllegalStateException("Method call not finished!");
                }
                org.apache.thrift.transport.TMemoryInputTransport memoryTransport = new org.apache.thrift.transport.TMemoryInputTransport(getFrameBuffer().array());
                org.apache.thrift.protocol.TProtocol prot = client.getProtocolFactory().getProtocol(memoryTransport);
                (new Client(prot)).recv_publish();
            }
        }

    }

    public static class Processor<I extends Iface> extends org.apache.thrift.TBaseProcessor<I> implements org.apache.thrift.TProcessor {
        private static final Logger LOGGER = LoggerFactory.getLogger(Processor.class.getName());
        public Processor(I iface) {
            super(iface, getProcessMap(new HashMap<String, org.apache.thrift.ProcessFunction<I, ? extends org.apache.thrift.TBase>>()));
        }

        protected Processor(I iface, Map<String,  org.apache.thrift.ProcessFunction<I, ? extends  org.apache.thrift.TBase>> processMap) {
            super(iface, getProcessMap(processMap));
        }

        private static <I extends Iface> Map<String,  org.apache.thrift.ProcessFunction<I, ? extends  org.apache.thrift.TBase>> getProcessMap(Map<String,  org.apache.thrift.ProcessFunction<I, ? extends  org.apache.thrift.TBase>> processMap) {
            processMap.put("defineType", new defineType());
            processMap.put("publish", new publish());
            return processMap;
        }

        private static class defineType<I extends Iface> extends org.apache.thrift.ProcessFunction<I, defineType_args> {
            public defineType() {
                super("defineType");
            }

            protected defineType_args getEmptyArgsInstance() {
                return new defineType_args();
            }

            protected defineType_result getResult(I iface, defineType_args args) throws org.apache.thrift.TException {
                defineType_result result = new defineType_result();
                try {
                    result.success = iface.defineType(args.sessionId, args.streamDefinition);
                } catch (org.wso2.carbon.agent.commons.thrift.exception.ThriftDifferentTypeDefinitionAlreadyDefinedException ade) {
                    result.ade = ade;
                } catch (org.wso2.carbon.agent.commons.thrift.exception.ThriftMalformedTypeDefinitionException mtd) {
                    result.mtd = mtd;
                } catch (org.wso2.carbon.agent.commons.thrift.exception.ThriftTypeDefinitionException tde) {
                    result.tde = tde;
                } catch (org.wso2.carbon.agent.commons.thrift.exception.ThriftSessionExpiredException se) {
                    result.se = se;
                }
                return result;
            }
        }

        private static class publish<I extends Iface> extends org.apache.thrift.ProcessFunction<I, publish_args> {
            public publish() {
                super("publish");
            }

            protected publish_args getEmptyArgsInstance() {
                return new publish_args();
            }

            protected publish_result getResult(I iface, publish_args args) throws org.apache.thrift.TException {
                publish_result result = new publish_result();
                try {
                    iface.publish(args.eventBundle);
                } catch (org.wso2.carbon.agent.commons.thrift.exception.ThriftUndefinedEventTypeException ue) {
                    result.ue = ue;
                } catch (org.wso2.carbon.agent.commons.thrift.exception.ThriftSessionExpiredException se) {
                    result.se = se;
                }
                return result;
            }
        }

    }

    public static class defineType_args implements org.apache.thrift.TBase<defineType_args, defineType_args._Fields>, java.io.Serializable, Cloneable   {
        private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("defineType_args");

        private static final org.apache.thrift.protocol.TField SESSION_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("sessionId", org.apache.thrift.protocol.TType.STRING, (short)1);
        private static final org.apache.thrift.protocol.TField STREAM_DEFINITION_FIELD_DESC = new org.apache.thrift.protocol.TField("streamDefinition", org.apache.thrift.protocol.TType.STRING, (short)2);

        private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
        static {
            schemes.put(StandardScheme.class, new defineType_argsStandardSchemeFactory());
            schemes.put(TupleScheme.class, new defineType_argsTupleSchemeFactory());
        }

        public String sessionId; // required
        public String streamDefinition; // required

        /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
        public enum _Fields implements org.apache.thrift.TFieldIdEnum {
            SESSION_ID((short)1, "sessionId"),
            STREAM_DEFINITION((short)2, "streamDefinition");

            private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

            static {
                for (_Fields field : EnumSet.allOf(_Fields.class)) {
                    byName.put(field.getFieldName(), field);
                }
            }

            /**
             * Find the _Fields constant that matches fieldId, or null if its not found.
             */
            public static _Fields findByThriftId(int fieldId) {
                switch(fieldId) {
                    case 1: // SESSION_ID
                        return SESSION_ID;
                    case 2: // STREAM_DEFINITION
                        return STREAM_DEFINITION;
                    default:
                        return null;
                }
            }

            /**
             * Find the _Fields constant that matches fieldId, throwing an exception
             * if it is not found.
             */
            public static _Fields findByThriftIdOrThrow(int fieldId) {
                _Fields fields = findByThriftId(fieldId);
                if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
                return fields;
            }

            /**
             * Find the _Fields constant that matches name, or null if its not found.
             */
            public static _Fields findByName(String name) {
                return byName.get(name);
            }

            private final short _thriftId;
            private final String _fieldName;

            _Fields(short thriftId, String fieldName) {
                _thriftId = thriftId;
                _fieldName = fieldName;
            }

            public short getThriftFieldId() {
                return _thriftId;
            }

            public String getFieldName() {
                return _fieldName;
            }
        }

        // isset id assignments
        public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
        static {
            Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
            tmpMap.put(_Fields.SESSION_ID, new org.apache.thrift.meta_data.FieldMetaData("sessionId", org.apache.thrift.TFieldRequirementType.DEFAULT,
                                                                                         new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
            tmpMap.put(_Fields.STREAM_DEFINITION, new org.apache.thrift.meta_data.FieldMetaData("streamDefinition", org.apache.thrift.TFieldRequirementType.DEFAULT,
                                                                                                new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
            metaDataMap = Collections.unmodifiableMap(tmpMap);
            org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(defineType_args.class, metaDataMap);
        }

        public defineType_args() {
        }

        public defineType_args(
                String sessionId,
                String streamDefinition)
        {
            this();
            this.sessionId = sessionId;
            this.streamDefinition = streamDefinition;
        }

        /**
         * Performs a deep copy on <i>other</i>.
         */
        public defineType_args(defineType_args other) {
            if (other.isSetSessionId()) {
                this.sessionId = other.sessionId;
            }
            if (other.isSetStreamDefinition()) {
                this.streamDefinition = other.streamDefinition;
            }
        }

        public defineType_args deepCopy() {
            return new defineType_args(this);
        }

        @Override
        public void clear() {
            this.sessionId = null;
            this.streamDefinition = null;
        }

        public String getSessionId() {
            return this.sessionId;
        }

        public defineType_args setSessionId(String sessionId) {
            this.sessionId = sessionId;
            return this;
        }

        public void unsetSessionId() {
            this.sessionId = null;
        }

        /** Returns true if field sessionId is set (has been assigned a value) and false otherwise */
        public boolean isSetSessionId() {
            return this.sessionId != null;
        }

        public void setSessionIdIsSet(boolean value) {
            if (!value) {
                this.sessionId = null;
            }
        }

        public String getStreamDefinition() {
            return this.streamDefinition;
        }

        public defineType_args setStreamDefinition(String streamDefinition) {
            this.streamDefinition = streamDefinition;
            return this;
        }

        public void unsetStreamDefinition() {
            this.streamDefinition = null;
        }

        /** Returns true if field streamDefinition is set (has been assigned a value) and false otherwise */
        public boolean isSetStreamDefinition() {
            return this.streamDefinition != null;
        }

        public void setStreamDefinitionIsSet(boolean value) {
            if (!value) {
                this.streamDefinition = null;
            }
        }

        public void setFieldValue(_Fields field, Object value) {
            switch (field) {
                case SESSION_ID:
                    if (value == null) {
                        unsetSessionId();
                    } else {
                        setSessionId((String)value);
                    }
                    break;

                case STREAM_DEFINITION:
                    if (value == null) {
                        unsetStreamDefinition();
                    } else {
                        setStreamDefinition((String)value);
                    }
                    break;

            }
        }

        public Object getFieldValue(_Fields field) {
            switch (field) {
                case SESSION_ID:
                    return getSessionId();

                case STREAM_DEFINITION:
                    return getStreamDefinition();

            }
            throw new IllegalStateException();
        }

        /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
        public boolean isSet(_Fields field) {
            if (field == null) {
                throw new IllegalArgumentException();
            }

            switch (field) {
                case SESSION_ID:
                    return isSetSessionId();
                case STREAM_DEFINITION:
                    return isSetStreamDefinition();
            }
            throw new IllegalStateException();
        }

        @Override
        public boolean equals(Object that) {
            if (that == null)
                return false;
            if (that instanceof defineType_args)
                return this.equals((defineType_args)that);
            return false;
        }

        public boolean equals(defineType_args that) {
            if (that == null)
                return false;

            boolean this_present_sessionId = true && this.isSetSessionId();
            boolean that_present_sessionId = true && that.isSetSessionId();
            if (this_present_sessionId || that_present_sessionId) {
                if (!(this_present_sessionId && that_present_sessionId))
                    return false;
                if (!this.sessionId.equals(that.sessionId))
                    return false;
            }

            boolean this_present_streamDefinition = true && this.isSetStreamDefinition();
            boolean that_present_streamDefinition = true && that.isSetStreamDefinition();
            if (this_present_streamDefinition || that_present_streamDefinition) {
                if (!(this_present_streamDefinition && that_present_streamDefinition))
                    return false;
                if (!this.streamDefinition.equals(that.streamDefinition))
                    return false;
            }

            return true;
        }

        @Override
        public int hashCode() {
            return 0;
        }

        public int compareTo(defineType_args other) {
            if (!getClass().equals(other.getClass())) {
                return getClass().getName().compareTo(other.getClass().getName());
            }

            int lastComparison = 0;
            defineType_args typedOther = (defineType_args)other;

            lastComparison = Boolean.valueOf(isSetSessionId()).compareTo(typedOther.isSetSessionId());
            if (lastComparison != 0) {
                return lastComparison;
            }
            if (isSetSessionId()) {
                lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.sessionId, typedOther.sessionId);
                if (lastComparison != 0) {
                    return lastComparison;
                }
            }
            lastComparison = Boolean.valueOf(isSetStreamDefinition()).compareTo(typedOther.isSetStreamDefinition());
            if (lastComparison != 0) {
                return lastComparison;
            }
            if (isSetStreamDefinition()) {
                lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.streamDefinition, typedOther.streamDefinition);
                if (lastComparison != 0) {
                    return lastComparison;
                }
            }
            return 0;
        }

        public _Fields fieldForId(int fieldId) {
            return _Fields.findByThriftId(fieldId);
        }

        public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
            schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
        }

        public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
            schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
        }

        @Override
        public String toString() {
            StringBuilder sb = new StringBuilder("defineType_args(");
            boolean first = true;

            sb.append("sessionId:");
            if (this.sessionId == null) {
                sb.append("null");
            } else {
                sb.append(this.sessionId);
            }
            first = false;
            if (!first) sb.append(", ");
            sb.append("streamDefinition:");
            if (this.streamDefinition == null) {
                sb.append("null");
            } else {
                sb.append(this.streamDefinition);
            }
            first = false;
            sb.append(")");
            return sb.toString();
        }

        public void validate() throws org.apache.thrift.TException {
            // check for required fields
        }

        private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
            try {
                write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
            } catch (org.apache.thrift.TException te) {
                throw new java.io.IOException(te);
            }
        }

        private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
            try {
                read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
            } catch (org.apache.thrift.TException te) {
                throw new java.io.IOException(te);
            }
        }

        private static class defineType_argsStandardSchemeFactory implements SchemeFactory {
            public defineType_argsStandardScheme getScheme() {
                return new defineType_argsStandardScheme();
            }
        }

        private static class defineType_argsStandardScheme extends StandardScheme<defineType_args> {

            public void read(org.apache.thrift.protocol.TProtocol iprot, defineType_args struct) throws org.apache.thrift.TException {
                org.apache.thrift.protocol.TField schemeField;
                iprot.readStructBegin();
                while (true)
                {
                    schemeField = iprot.readFieldBegin();
                    if (schemeField.type == org.apache.thrift.protocol.TType.STOP) {
                        break;
                    }
                    switch (schemeField.id) {
                        case 1: // SESSION_ID
                            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
                                struct.sessionId = iprot.readString();
                                struct.setSessionIdIsSet(true);
                            } else {
                                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                            }
                            break;
                        case 2: // STREAM_DEFINITION
                            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
                                struct.streamDefinition = iprot.readString();
                                struct.setStreamDefinitionIsSet(true);
                            } else {
                                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                            }
                            break;
                        default:
                            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                    }
                    iprot.readFieldEnd();
                }
                iprot.readStructEnd();

                // check for required fields of primitive type, which can't be checked in the validate method
                struct.validate();
            }

            public void write(org.apache.thrift.protocol.TProtocol oprot, defineType_args struct) throws org.apache.thrift.TException {
                struct.validate();

                oprot.writeStructBegin(STRUCT_DESC);
                if (struct.sessionId != null) {
                    oprot.writeFieldBegin(SESSION_ID_FIELD_DESC);
                    oprot.writeString(struct.sessionId);
                    oprot.writeFieldEnd();
                }
                if (struct.streamDefinition != null) {
                    oprot.writeFieldBegin(STREAM_DEFINITION_FIELD_DESC);
                    oprot.writeString(struct.streamDefinition);
                    oprot.writeFieldEnd();
                }
                oprot.writeFieldStop();
                oprot.writeStructEnd();
            }

        }

        private static class defineType_argsTupleSchemeFactory implements SchemeFactory {
            public defineType_argsTupleScheme getScheme() {
                return new defineType_argsTupleScheme();
            }
        }

        private static class defineType_argsTupleScheme extends TupleScheme<defineType_args> {

            @Override
            public void write(org.apache.thrift.protocol.TProtocol prot, defineType_args struct) throws org.apache.thrift.TException {
                TTupleProtocol oprot = (TTupleProtocol) prot;
                BitSet optionals = new BitSet();
                if (struct.isSetSessionId()) {
                    optionals.set(0);
                }
                if (struct.isSetStreamDefinition()) {
                    optionals.set(1);
                }
                oprot.writeBitSet(optionals, 2);
                if (struct.isSetSessionId()) {
                    oprot.writeString(struct.sessionId);
                }
                if (struct.isSetStreamDefinition()) {
                    oprot.writeString(struct.streamDefinition);
                }
            }

            @Override
            public void read(org.apache.thrift.protocol.TProtocol prot, defineType_args struct) throws org.apache.thrift.TException {
                TTupleProtocol iprot = (TTupleProtocol) prot;
                BitSet incoming = iprot.readBitSet(2);
                if (incoming.get(0)) {
                    struct.sessionId = iprot.readString();
                    struct.setSessionIdIsSet(true);
                }
                if (incoming.get(1)) {
                    struct.streamDefinition = iprot.readString();
                    struct.setStreamDefinitionIsSet(true);
                }
            }
        }

    }

    public static class defineType_result implements org.apache.thrift.TBase<defineType_result, defineType_result._Fields>, java.io.Serializable, Cloneable   {
        private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("defineType_result");

        private static final org.apache.thrift.protocol.TField SUCCESS_FIELD_DESC = new org.apache.thrift.protocol.TField("success", org.apache.thrift.protocol.TType.STRING, (short)0);
        private static final org.apache.thrift.protocol.TField ADE_FIELD_DESC = new org.apache.thrift.protocol.TField("ade", org.apache.thrift.protocol.TType.STRUCT, (short)1);
        private static final org.apache.thrift.protocol.TField MTD_FIELD_DESC = new org.apache.thrift.protocol.TField("mtd", org.apache.thrift.protocol.TType.STRUCT, (short)2);
        private static final org.apache.thrift.protocol.TField TDE_FIELD_DESC = new org.apache.thrift.protocol.TField("tde", org.apache.thrift.protocol.TType.STRUCT, (short)3);
        private static final org.apache.thrift.protocol.TField SE_FIELD_DESC = new org.apache.thrift.protocol.TField("se", org.apache.thrift.protocol.TType.STRUCT, (short)4);

        private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
        static {
            schemes.put(StandardScheme.class, new defineType_resultStandardSchemeFactory());
            schemes.put(TupleScheme.class, new defineType_resultTupleSchemeFactory());
        }

        public String success; // required
        public org.wso2.carbon.agent.commons.thrift.exception.ThriftDifferentTypeDefinitionAlreadyDefinedException ade; // required
        public org.wso2.carbon.agent.commons.thrift.exception.ThriftMalformedTypeDefinitionException mtd; // required
        public org.wso2.carbon.agent.commons.thrift.exception.ThriftTypeDefinitionException tde; // required
        public org.wso2.carbon.agent.commons.thrift.exception.ThriftSessionExpiredException se; // required

        /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
        public enum _Fields implements org.apache.thrift.TFieldIdEnum {
            SUCCESS((short)0, "success"),
            ADE((short)1, "ade"),
            MTD((short)2, "mtd"),
            TDE((short)3, "tde"),
            SE((short)4, "se");

            private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

            static {
                for (_Fields field : EnumSet.allOf(_Fields.class)) {
                    byName.put(field.getFieldName(), field);
                }
            }

            /**
             * Find the _Fields constant that matches fieldId, or null if its not found.
             */
            public static _Fields findByThriftId(int fieldId) {
                switch(fieldId) {
                    case 0: // SUCCESS
                        return SUCCESS;
                    case 1: // ADE
                        return ADE;
                    case 2: // MTD
                        return MTD;
                    case 3: // TDE
                        return TDE;
                    case 4: // SE
                        return SE;
                    default:
                        return null;
                }
            }

            /**
             * Find the _Fields constant that matches fieldId, throwing an exception
             * if it is not found.
             */
            public static _Fields findByThriftIdOrThrow(int fieldId) {
                _Fields fields = findByThriftId(fieldId);
                if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
                return fields;
            }

            /**
             * Find the _Fields constant that matches name, or null if its not found.
             */
            public static _Fields findByName(String name) {
                return byName.get(name);
            }

            private final short _thriftId;
            private final String _fieldName;

            _Fields(short thriftId, String fieldName) {
                _thriftId = thriftId;
                _fieldName = fieldName;
            }

            public short getThriftFieldId() {
                return _thriftId;
            }

            public String getFieldName() {
                return _fieldName;
            }
        }

        // isset id assignments
        public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
        static {
            Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
            tmpMap.put(_Fields.SUCCESS, new org.apache.thrift.meta_data.FieldMetaData("success", org.apache.thrift.TFieldRequirementType.DEFAULT,
                                                                                      new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
            tmpMap.put(_Fields.ADE, new org.apache.thrift.meta_data.FieldMetaData("ade", org.apache.thrift.TFieldRequirementType.DEFAULT,
                                                                                  new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRUCT)));
            tmpMap.put(_Fields.MTD, new org.apache.thrift.meta_data.FieldMetaData("mtd", org.apache.thrift.TFieldRequirementType.DEFAULT,
                                                                                  new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRUCT)));
            tmpMap.put(_Fields.TDE, new org.apache.thrift.meta_data.FieldMetaData("tde", org.apache.thrift.TFieldRequirementType.DEFAULT,
                                                                                  new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRUCT)));
            tmpMap.put(_Fields.SE, new org.apache.thrift.meta_data.FieldMetaData("se", org.apache.thrift.TFieldRequirementType.DEFAULT,
                                                                                 new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRUCT)));
            metaDataMap = Collections.unmodifiableMap(tmpMap);
            org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(defineType_result.class, metaDataMap);
        }

        public defineType_result() {
        }

        public defineType_result(
                String success,
                org.wso2.carbon.agent.commons.thrift.exception.ThriftDifferentTypeDefinitionAlreadyDefinedException ade,
                org.wso2.carbon.agent.commons.thrift.exception.ThriftMalformedTypeDefinitionException mtd,
                org.wso2.carbon.agent.commons.thrift.exception.ThriftTypeDefinitionException tde,
                org.wso2.carbon.agent.commons.thrift.exception.ThriftSessionExpiredException se)
        {
            this();
            this.success = success;
            this.ade = ade;
            this.mtd = mtd;
            this.tde = tde;
            this.se = se;
        }

        /**
         * Performs a deep copy on <i>other</i>.
         */
        public defineType_result(defineType_result other) {
            if (other.isSetSuccess()) {
                this.success = other.success;
            }
            if (other.isSetAde()) {
                this.ade = new org.wso2.carbon.agent.commons.thrift.exception.ThriftDifferentTypeDefinitionAlreadyDefinedException(other.ade);
            }
            if (other.isSetMtd()) {
                this.mtd = new org.wso2.carbon.agent.commons.thrift.exception.ThriftMalformedTypeDefinitionException(other.mtd);
            }
            if (other.isSetTde()) {
                this.tde = new org.wso2.carbon.agent.commons.thrift.exception.ThriftTypeDefinitionException(other.tde);
            }
            if (other.isSetSe()) {
                this.se = new org.wso2.carbon.agent.commons.thrift.exception.ThriftSessionExpiredException(other.se);
            }
        }

        public defineType_result deepCopy() {
            return new defineType_result(this);
        }

        @Override
        public void clear() {
            this.success = null;
            this.ade = null;
            this.mtd = null;
            this.tde = null;
            this.se = null;
        }

        public String getSuccess() {
            return this.success;
        }

        public defineType_result setSuccess(String success) {
            this.success = success;
            return this;
        }

        public void unsetSuccess() {
            this.success = null;
        }

        /** Returns true if field success is set (has been assigned a value) and false otherwise */
        public boolean isSetSuccess() {
            return this.success != null;
        }

        public void setSuccessIsSet(boolean value) {
            if (!value) {
                this.success = null;
            }
        }

        public org.wso2.carbon.agent.commons.thrift.exception.ThriftDifferentTypeDefinitionAlreadyDefinedException getAde() {
            return this.ade;
        }

        public defineType_result setAde(org.wso2.carbon.agent.commons.thrift.exception.ThriftDifferentTypeDefinitionAlreadyDefinedException ade) {
            this.ade = ade;
            return this;
        }

        public void unsetAde() {
            this.ade = null;
        }

        /** Returns true if field ade is set (has been assigned a value) and false otherwise */
        public boolean isSetAde() {
            return this.ade != null;
        }

        public void setAdeIsSet(boolean value) {
            if (!value) {
                this.ade = null;
            }
        }

        public org.wso2.carbon.agent.commons.thrift.exception.ThriftMalformedTypeDefinitionException getMtd() {
            return this.mtd;
        }

        public defineType_result setMtd(org.wso2.carbon.agent.commons.thrift.exception.ThriftMalformedTypeDefinitionException mtd) {
            this.mtd = mtd;
            return this;
        }

        public void unsetMtd() {
            this.mtd = null;
        }

        /** Returns true if field mtd is set (has been assigned a value) and false otherwise */
        public boolean isSetMtd() {
            return this.mtd != null;
        }

        public void setMtdIsSet(boolean value) {
            if (!value) {
                this.mtd = null;
            }
        }

        public org.wso2.carbon.agent.commons.thrift.exception.ThriftTypeDefinitionException getTde() {
            return this.tde;
        }

        public defineType_result setTde(org.wso2.carbon.agent.commons.thrift.exception.ThriftTypeDefinitionException tde) {
            this.tde = tde;
            return this;
        }

        public void unsetTde() {
            this.tde = null;
        }

        /** Returns true if field tde is set (has been assigned a value) and false otherwise */
        public boolean isSetTde() {
            return this.tde != null;
        }

        public void setTdeIsSet(boolean value) {
            if (!value) {
                this.tde = null;
            }
        }

        public org.wso2.carbon.agent.commons.thrift.exception.ThriftSessionExpiredException getSe() {
            return this.se;
        }

        public defineType_result setSe(org.wso2.carbon.agent.commons.thrift.exception.ThriftSessionExpiredException se) {
            this.se = se;
            return this;
        }

        public void unsetSe() {
            this.se = null;
        }

        /** Returns true if field se is set (has been assigned a value) and false otherwise */
        public boolean isSetSe() {
            return this.se != null;
        }

        public void setSeIsSet(boolean value) {
            if (!value) {
                this.se = null;
            }
        }

        public void setFieldValue(_Fields field, Object value) {
            switch (field) {
                case SUCCESS:
                    if (value == null) {
                        unsetSuccess();
                    } else {
                        setSuccess((String)value);
                    }
                    break;

                case ADE:
                    if (value == null) {
                        unsetAde();
                    } else {
                        setAde((org.wso2.carbon.agent.commons.thrift.exception.ThriftDifferentTypeDefinitionAlreadyDefinedException)value);
                    }
                    break;

                case MTD:
                    if (value == null) {
                        unsetMtd();
                    } else {
                        setMtd((org.wso2.carbon.agent.commons.thrift.exception.ThriftMalformedTypeDefinitionException)value);
                    }
                    break;

                case TDE:
                    if (value == null) {
                        unsetTde();
                    } else {
                        setTde((org.wso2.carbon.agent.commons.thrift.exception.ThriftTypeDefinitionException)value);
                    }
                    break;

                case SE:
                    if (value == null) {
                        unsetSe();
                    } else {
                        setSe((org.wso2.carbon.agent.commons.thrift.exception.ThriftSessionExpiredException)value);
                    }
                    break;

            }
        }

        public Object getFieldValue(_Fields field) {
            switch (field) {
                case SUCCESS:
                    return getSuccess();

                case ADE:
                    return getAde();

                case MTD:
                    return getMtd();

                case TDE:
                    return getTde();

                case SE:
                    return getSe();

            }
            throw new IllegalStateException();
        }

        /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
        public boolean isSet(_Fields field) {
            if (field == null) {
                throw new IllegalArgumentException();
            }

            switch (field) {
                case SUCCESS:
                    return isSetSuccess();
                case ADE:
                    return isSetAde();
                case MTD:
                    return isSetMtd();
                case TDE:
                    return isSetTde();
                case SE:
                    return isSetSe();
            }
            throw new IllegalStateException();
        }

        @Override
        public boolean equals(Object that) {
            if (that == null)
                return false;
            if (that instanceof defineType_result)
                return this.equals((defineType_result)that);
            return false;
        }

        public boolean equals(defineType_result that) {
            if (that == null)
                return false;

            boolean this_present_success = true && this.isSetSuccess();
            boolean that_present_success = true && that.isSetSuccess();
            if (this_present_success || that_present_success) {
                if (!(this_present_success && that_present_success))
                    return false;
                if (!this.success.equals(that.success))
                    return false;
            }

            boolean this_present_ade = true && this.isSetAde();
            boolean that_present_ade = true && that.isSetAde();
            if (this_present_ade || that_present_ade) {
                if (!(this_present_ade && that_present_ade))
                    return false;
                if (!this.ade.equals(that.ade))
                    return false;
            }

            boolean this_present_mtd = true && this.isSetMtd();
            boolean that_present_mtd = true && that.isSetMtd();
            if (this_present_mtd || that_present_mtd) {
                if (!(this_present_mtd && that_present_mtd))
                    return false;
                if (!this.mtd.equals(that.mtd))
                    return false;
            }

            boolean this_present_tde = true && this.isSetTde();
            boolean that_present_tde = true && that.isSetTde();
            if (this_present_tde || that_present_tde) {
                if (!(this_present_tde && that_present_tde))
                    return false;
                if (!this.tde.equals(that.tde))
                    return false;
            }

            boolean this_present_se = true && this.isSetSe();
            boolean that_present_se = true && that.isSetSe();
            if (this_present_se || that_present_se) {
                if (!(this_present_se && that_present_se))
                    return false;
                if (!this.se.equals(that.se))
                    return false;
            }

            return true;
        }

        @Override
        public int hashCode() {
            return 0;
        }

        public int compareTo(defineType_result other) {
            if (!getClass().equals(other.getClass())) {
                return getClass().getName().compareTo(other.getClass().getName());
            }

            int lastComparison = 0;
            defineType_result typedOther = (defineType_result)other;

            lastComparison = Boolean.valueOf(isSetSuccess()).compareTo(typedOther.isSetSuccess());
            if (lastComparison != 0) {
                return lastComparison;
            }
            if (isSetSuccess()) {
                lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.success, typedOther.success);
                if (lastComparison != 0) {
                    return lastComparison;
                }
            }
            lastComparison = Boolean.valueOf(isSetAde()).compareTo(typedOther.isSetAde());
            if (lastComparison != 0) {
                return lastComparison;
            }
            if (isSetAde()) {
                lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.ade, typedOther.ade);
                if (lastComparison != 0) {
                    return lastComparison;
                }
            }
            lastComparison = Boolean.valueOf(isSetMtd()).compareTo(typedOther.isSetMtd());
            if (lastComparison != 0) {
                return lastComparison;
            }
            if (isSetMtd()) {
                lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.mtd, typedOther.mtd);
                if (lastComparison != 0) {
                    return lastComparison;
                }
            }
            lastComparison = Boolean.valueOf(isSetTde()).compareTo(typedOther.isSetTde());
            if (lastComparison != 0) {
                return lastComparison;
            }
            if (isSetTde()) {
                lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.tde, typedOther.tde);
                if (lastComparison != 0) {
                    return lastComparison;
                }
            }
            lastComparison = Boolean.valueOf(isSetSe()).compareTo(typedOther.isSetSe());
            if (lastComparison != 0) {
                return lastComparison;
            }
            if (isSetSe()) {
                lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.se, typedOther.se);
                if (lastComparison != 0) {
                    return lastComparison;
                }
            }
            return 0;
        }

        public _Fields fieldForId(int fieldId) {
            return _Fields.findByThriftId(fieldId);
        }

        public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
            schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
        }

        public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
            schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
        }

        @Override
        public String toString() {
            StringBuilder sb = new StringBuilder("defineType_result(");
            boolean first = true;

            sb.append("success:");
            if (this.success == null) {
                sb.append("null");
            } else {
                sb.append(this.success);
            }
            first = false;
            if (!first) sb.append(", ");
            sb.append("ade:");
            if (this.ade == null) {
                sb.append("null");
            } else {
                sb.append(this.ade);
            }
            first = false;
            if (!first) sb.append(", ");
            sb.append("mtd:");
            if (this.mtd == null) {
                sb.append("null");
            } else {
                sb.append(this.mtd);
            }
            first = false;
            if (!first) sb.append(", ");
            sb.append("tde:");
            if (this.tde == null) {
                sb.append("null");
            } else {
                sb.append(this.tde);
            }
            first = false;
            if (!first) sb.append(", ");
            sb.append("se:");
            if (this.se == null) {
                sb.append("null");
            } else {
                sb.append(this.se);
            }
            first = false;
            sb.append(")");
            return sb.toString();
        }

        public void validate() throws org.apache.thrift.TException {
            // check for required fields
        }

        private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
            try {
                write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
            } catch (org.apache.thrift.TException te) {
                throw new java.io.IOException(te);
            }
        }

        private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
            try {
                read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
            } catch (org.apache.thrift.TException te) {
                throw new java.io.IOException(te);
            }
        }

        private static class defineType_resultStandardSchemeFactory implements SchemeFactory {
            public defineType_resultStandardScheme getScheme() {
                return new defineType_resultStandardScheme();
            }
        }

        private static class defineType_resultStandardScheme extends StandardScheme<defineType_result> {

            public void read(org.apache.thrift.protocol.TProtocol iprot, defineType_result struct) throws org.apache.thrift.TException {
                org.apache.thrift.protocol.TField schemeField;
                iprot.readStructBegin();
                while (true)
                {
                    schemeField = iprot.readFieldBegin();
                    if (schemeField.type == org.apache.thrift.protocol.TType.STOP) {
                        break;
                    }
                    switch (schemeField.id) {
                        case 0: // SUCCESS
                            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
                                struct.success = iprot.readString();
                                struct.setSuccessIsSet(true);
                            } else {
                                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                            }
                            break;
                        case 1: // ADE
                            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
                                struct.ade = new org.wso2.carbon.agent.commons.thrift.exception.ThriftDifferentTypeDefinitionAlreadyDefinedException();
                                struct.ade.read(iprot);
                                struct.setAdeIsSet(true);
                            } else {
                                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                            }
                            break;
                        case 2: // MTD
                            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
                                struct.mtd = new org.wso2.carbon.agent.commons.thrift.exception.ThriftMalformedTypeDefinitionException();
                                struct.mtd.read(iprot);
                                struct.setMtdIsSet(true);
                            } else {
                                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                            }
                            break;
                        case 3: // TDE
                            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
                                struct.tde = new org.wso2.carbon.agent.commons.thrift.exception.ThriftTypeDefinitionException();
                                struct.tde.read(iprot);
                                struct.setTdeIsSet(true);
                            } else {
                                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                            }
                            break;
                        case 4: // SE
                            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
                                struct.se = new org.wso2.carbon.agent.commons.thrift.exception.ThriftSessionExpiredException();
                                struct.se.read(iprot);
                                struct.setSeIsSet(true);
                            } else {
                                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                            }
                            break;
                        default:
                            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                    }
                    iprot.readFieldEnd();
                }
                iprot.readStructEnd();

                // check for required fields of primitive type, which can't be checked in the validate method
                struct.validate();
            }

            public void write(org.apache.thrift.protocol.TProtocol oprot, defineType_result struct) throws org.apache.thrift.TException {
                struct.validate();

                oprot.writeStructBegin(STRUCT_DESC);
                if (struct.success != null) {
                    oprot.writeFieldBegin(SUCCESS_FIELD_DESC);
                    oprot.writeString(struct.success);
                    oprot.writeFieldEnd();
                }
                if (struct.ade != null) {
                    oprot.writeFieldBegin(ADE_FIELD_DESC);
                    struct.ade.write(oprot);
                    oprot.writeFieldEnd();
                }
                if (struct.mtd != null) {
                    oprot.writeFieldBegin(MTD_FIELD_DESC);
                    struct.mtd.write(oprot);
                    oprot.writeFieldEnd();
                }
                if (struct.tde != null) {
                    oprot.writeFieldBegin(TDE_FIELD_DESC);
                    struct.tde.write(oprot);
                    oprot.writeFieldEnd();
                }
                if (struct.se != null) {
                    oprot.writeFieldBegin(SE_FIELD_DESC);
                    struct.se.write(oprot);
                    oprot.writeFieldEnd();
                }
                oprot.writeFieldStop();
                oprot.writeStructEnd();
            }

        }

        private static class defineType_resultTupleSchemeFactory implements SchemeFactory {
            public defineType_resultTupleScheme getScheme() {
                return new defineType_resultTupleScheme();
            }
        }

        private static class defineType_resultTupleScheme extends TupleScheme<defineType_result> {

            @Override
            public void write(org.apache.thrift.protocol.TProtocol prot, defineType_result struct) throws org.apache.thrift.TException {
                TTupleProtocol oprot = (TTupleProtocol) prot;
                BitSet optionals = new BitSet();
                if (struct.isSetSuccess()) {
                    optionals.set(0);
                }
                if (struct.isSetAde()) {
                    optionals.set(1);
                }
                if (struct.isSetMtd()) {
                    optionals.set(2);
                }
                if (struct.isSetTde()) {
                    optionals.set(3);
                }
                if (struct.isSetSe()) {
                    optionals.set(4);
                }
                oprot.writeBitSet(optionals, 5);
                if (struct.isSetSuccess()) {
                    oprot.writeString(struct.success);
                }
                if (struct.isSetAde()) {
                    struct.ade.write(oprot);
                }
                if (struct.isSetMtd()) {
                    struct.mtd.write(oprot);
                }
                if (struct.isSetTde()) {
                    struct.tde.write(oprot);
                }
                if (struct.isSetSe()) {
                    struct.se.write(oprot);
                }
            }

            @Override
            public void read(org.apache.thrift.protocol.TProtocol prot, defineType_result struct) throws org.apache.thrift.TException {
                TTupleProtocol iprot = (TTupleProtocol) prot;
                BitSet incoming = iprot.readBitSet(5);
                if (incoming.get(0)) {
                    struct.success = iprot.readString();
                    struct.setSuccessIsSet(true);
                }
                if (incoming.get(1)) {
                    struct.ade = new org.wso2.carbon.agent.commons.thrift.exception.ThriftDifferentTypeDefinitionAlreadyDefinedException();
                    struct.ade.read(iprot);
                    struct.setAdeIsSet(true);
                }
                if (incoming.get(2)) {
                    struct.mtd = new org.wso2.carbon.agent.commons.thrift.exception.ThriftMalformedTypeDefinitionException();
                    struct.mtd.read(iprot);
                    struct.setMtdIsSet(true);
                }
                if (incoming.get(3)) {
                    struct.tde = new org.wso2.carbon.agent.commons.thrift.exception.ThriftTypeDefinitionException();
                    struct.tde.read(iprot);
                    struct.setTdeIsSet(true);
                }
                if (incoming.get(4)) {
                    struct.se = new org.wso2.carbon.agent.commons.thrift.exception.ThriftSessionExpiredException();
                    struct.se.read(iprot);
                    struct.setSeIsSet(true);
                }
            }
        }

    }

    public static class publish_args implements org.apache.thrift.TBase<publish_args, publish_args._Fields>, java.io.Serializable, Cloneable   {
        private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("publish_args");

        private static final org.apache.thrift.protocol.TField EVENT_BUNDLE_FIELD_DESC = new org.apache.thrift.protocol.TField("eventBundle", org.apache.thrift.protocol.TType.STRUCT, (short)1);

        private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
        static {
            schemes.put(StandardScheme.class, new publish_argsStandardSchemeFactory());
            schemes.put(TupleScheme.class, new publish_argsTupleSchemeFactory());
        }

        public org.wso2.carbon.agent.commons.thrift.data.ThriftEventBundle eventBundle; // required

        /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
        public enum _Fields implements org.apache.thrift.TFieldIdEnum {
            EVENT_BUNDLE((short)1, "eventBundle");

            private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

            static {
                for (_Fields field : EnumSet.allOf(_Fields.class)) {
                    byName.put(field.getFieldName(), field);
                }
            }

            /**
             * Find the _Fields constant that matches fieldId, or null if its not found.
             */
            public static _Fields findByThriftId(int fieldId) {
                switch(fieldId) {
                    case 1: // EVENT_BUNDLE
                        return EVENT_BUNDLE;
                    default:
                        return null;
                }
            }

            /**
             * Find the _Fields constant that matches fieldId, throwing an exception
             * if it is not found.
             */
            public static _Fields findByThriftIdOrThrow(int fieldId) {
                _Fields fields = findByThriftId(fieldId);
                if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
                return fields;
            }

            /**
             * Find the _Fields constant that matches name, or null if its not found.
             */
            public static _Fields findByName(String name) {
                return byName.get(name);
            }

            private final short _thriftId;
            private final String _fieldName;

            _Fields(short thriftId, String fieldName) {
                _thriftId = thriftId;
                _fieldName = fieldName;
            }

            public short getThriftFieldId() {
                return _thriftId;
            }

            public String getFieldName() {
                return _fieldName;
            }
        }

        // isset id assignments
        public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
        static {
            Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
            tmpMap.put(_Fields.EVENT_BUNDLE, new org.apache.thrift.meta_data.FieldMetaData("eventBundle", org.apache.thrift.TFieldRequirementType.DEFAULT,
                                                                                           new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, org.wso2.carbon.agent.commons.thrift.data.ThriftEventBundle.class)));
            metaDataMap = Collections.unmodifiableMap(tmpMap);
            org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(publish_args.class, metaDataMap);
        }

        public publish_args() {
        }

        public publish_args(
                org.wso2.carbon.agent.commons.thrift.data.ThriftEventBundle eventBundle)
        {
            this();
            this.eventBundle = eventBundle;
        }

        /**
         * Performs a deep copy on <i>other</i>.
         */
        public publish_args(publish_args other) {
            if (other.isSetEventBundle()) {
                this.eventBundle = new org.wso2.carbon.agent.commons.thrift.data.ThriftEventBundle(other.eventBundle);
            }
        }

        public publish_args deepCopy() {
            return new publish_args(this);
        }

        @Override
        public void clear() {
            this.eventBundle = null;
        }

        public org.wso2.carbon.agent.commons.thrift.data.ThriftEventBundle getEventBundle() {
            return this.eventBundle;
        }

        public publish_args setEventBundle(org.wso2.carbon.agent.commons.thrift.data.ThriftEventBundle eventBundle) {
            this.eventBundle = eventBundle;
            return this;
        }

        public void unsetEventBundle() {
            this.eventBundle = null;
        }

        /** Returns true if field eventBundle is set (has been assigned a value) and false otherwise */
        public boolean isSetEventBundle() {
            return this.eventBundle != null;
        }

        public void setEventBundleIsSet(boolean value) {
            if (!value) {
                this.eventBundle = null;
            }
        }

        public void setFieldValue(_Fields field, Object value) {
            switch (field) {
                case EVENT_BUNDLE:
                    if (value == null) {
                        unsetEventBundle();
                    } else {
                        setEventBundle((org.wso2.carbon.agent.commons.thrift.data.ThriftEventBundle)value);
                    }
                    break;

            }
        }

        public Object getFieldValue(_Fields field) {
            switch (field) {
                case EVENT_BUNDLE:
                    return getEventBundle();

            }
            throw new IllegalStateException();
        }

        /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
        public boolean isSet(_Fields field) {
            if (field == null) {
                throw new IllegalArgumentException();
            }

            switch (field) {
                case EVENT_BUNDLE:
                    return isSetEventBundle();
            }
            throw new IllegalStateException();
        }

        @Override
        public boolean equals(Object that) {
            if (that == null)
                return false;
            if (that instanceof publish_args)
                return this.equals((publish_args)that);
            return false;
        }

        public boolean equals(publish_args that) {
            if (that == null)
                return false;

            boolean this_present_eventBundle = true && this.isSetEventBundle();
            boolean that_present_eventBundle = true && that.isSetEventBundle();
            if (this_present_eventBundle || that_present_eventBundle) {
                if (!(this_present_eventBundle && that_present_eventBundle))
                    return false;
                if (!this.eventBundle.equals(that.eventBundle))
                    return false;
            }

            return true;
        }

        @Override
        public int hashCode() {
            return 0;
        }

        public int compareTo(publish_args other) {
            if (!getClass().equals(other.getClass())) {
                return getClass().getName().compareTo(other.getClass().getName());
            }

            int lastComparison = 0;
            publish_args typedOther = (publish_args)other;

            lastComparison = Boolean.valueOf(isSetEventBundle()).compareTo(typedOther.isSetEventBundle());
            if (lastComparison != 0) {
                return lastComparison;
            }
            if (isSetEventBundle()) {
                lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.eventBundle, typedOther.eventBundle);
                if (lastComparison != 0) {
                    return lastComparison;
                }
            }
            return 0;
        }

        public _Fields fieldForId(int fieldId) {
            return _Fields.findByThriftId(fieldId);
        }

        public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
            schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
        }

        public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
            schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
        }

        @Override
        public String toString() {
            StringBuilder sb = new StringBuilder("publish_args(");
            boolean first = true;

            sb.append("eventBundle:");
            if (this.eventBundle == null) {
                sb.append("null");
            } else {
                sb.append(this.eventBundle);
            }
            first = false;
            sb.append(")");
            return sb.toString();
        }

        public void validate() throws org.apache.thrift.TException {
            // check for required fields
        }

        private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
            try {
                write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
            } catch (org.apache.thrift.TException te) {
                throw new java.io.IOException(te);
            }
        }

        private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
            try {
                read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
            } catch (org.apache.thrift.TException te) {
                throw new java.io.IOException(te);
            }
        }

        private static class publish_argsStandardSchemeFactory implements SchemeFactory {
            public publish_argsStandardScheme getScheme() {
                return new publish_argsStandardScheme();
            }
        }

        private static class publish_argsStandardScheme extends StandardScheme<publish_args> {

            public void read(org.apache.thrift.protocol.TProtocol iprot, publish_args struct) throws org.apache.thrift.TException {
                org.apache.thrift.protocol.TField schemeField;
                iprot.readStructBegin();
                while (true)
                {
                    schemeField = iprot.readFieldBegin();
                    if (schemeField.type == org.apache.thrift.protocol.TType.STOP) {
                        break;
                    }
                    switch (schemeField.id) {
                        case 1: // EVENT_BUNDLE
                            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
                                struct.eventBundle = new org.wso2.carbon.agent.commons.thrift.data.ThriftEventBundle();
                                struct.eventBundle.read(iprot);
                                struct.setEventBundleIsSet(true);
                            } else {
                                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                            }
                            break;
                        default:
                            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                    }
                    iprot.readFieldEnd();
                }
                iprot.readStructEnd();

                // check for required fields of primitive type, which can't be checked in the validate method
                struct.validate();
            }

            public void write(org.apache.thrift.protocol.TProtocol oprot, publish_args struct) throws org.apache.thrift.TException {
                struct.validate();

                oprot.writeStructBegin(STRUCT_DESC);
                if (struct.eventBundle != null) {
                    oprot.writeFieldBegin(EVENT_BUNDLE_FIELD_DESC);
                    struct.eventBundle.write(oprot);
                    oprot.writeFieldEnd();
                }
                oprot.writeFieldStop();
                oprot.writeStructEnd();
            }

        }

        private static class publish_argsTupleSchemeFactory implements SchemeFactory {
            public publish_argsTupleScheme getScheme() {
                return new publish_argsTupleScheme();
            }
        }

        private static class publish_argsTupleScheme extends TupleScheme<publish_args> {

            @Override
            public void write(org.apache.thrift.protocol.TProtocol prot, publish_args struct) throws org.apache.thrift.TException {
                TTupleProtocol oprot = (TTupleProtocol) prot;
                BitSet optionals = new BitSet();
                if (struct.isSetEventBundle()) {
                    optionals.set(0);
                }
                oprot.writeBitSet(optionals, 1);
                if (struct.isSetEventBundle()) {
                    struct.eventBundle.write(oprot);
                }
            }

            @Override
            public void read(org.apache.thrift.protocol.TProtocol prot, publish_args struct) throws org.apache.thrift.TException {
                TTupleProtocol iprot = (TTupleProtocol) prot;
                BitSet incoming = iprot.readBitSet(1);
                if (incoming.get(0)) {
                    struct.eventBundle = new org.wso2.carbon.agent.commons.thrift.data.ThriftEventBundle();
                    struct.eventBundle.read(iprot);
                    struct.setEventBundleIsSet(true);
                }
            }
        }

    }

    public static class publish_result implements org.apache.thrift.TBase<publish_result, publish_result._Fields>, java.io.Serializable, Cloneable   {
        private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("publish_result");

        private static final org.apache.thrift.protocol.TField UE_FIELD_DESC = new org.apache.thrift.protocol.TField("ue", org.apache.thrift.protocol.TType.STRUCT, (short)1);
        private static final org.apache.thrift.protocol.TField SE_FIELD_DESC = new org.apache.thrift.protocol.TField("se", org.apache.thrift.protocol.TType.STRUCT, (short)2);

        private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
        static {
            schemes.put(StandardScheme.class, new publish_resultStandardSchemeFactory());
            schemes.put(TupleScheme.class, new publish_resultTupleSchemeFactory());
        }

        public org.wso2.carbon.agent.commons.thrift.exception.ThriftUndefinedEventTypeException ue; // required
        public org.wso2.carbon.agent.commons.thrift.exception.ThriftSessionExpiredException se; // required

        /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
        public enum _Fields implements org.apache.thrift.TFieldIdEnum {
            UE((short)1, "ue"),
            SE((short)2, "se");

            private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

            static {
                for (_Fields field : EnumSet.allOf(_Fields.class)) {
                    byName.put(field.getFieldName(), field);
                }
            }

            /**
             * Find the _Fields constant that matches fieldId, or null if its not found.
             */
            public static _Fields findByThriftId(int fieldId) {
                switch(fieldId) {
                    case 1: // UE
                        return UE;
                    case 2: // SE
                        return SE;
                    default:
                        return null;
                }
            }

            /**
             * Find the _Fields constant that matches fieldId, throwing an exception
             * if it is not found.
             */
            public static _Fields findByThriftIdOrThrow(int fieldId) {
                _Fields fields = findByThriftId(fieldId);
                if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
                return fields;
            }

            /**
             * Find the _Fields constant that matches name, or null if its not found.
             */
            public static _Fields findByName(String name) {
                return byName.get(name);
            }

            private final short _thriftId;
            private final String _fieldName;

            _Fields(short thriftId, String fieldName) {
                _thriftId = thriftId;
                _fieldName = fieldName;
            }

            public short getThriftFieldId() {
                return _thriftId;
            }

            public String getFieldName() {
                return _fieldName;
            }
        }

        // isset id assignments
        public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
        static {
            Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
            tmpMap.put(_Fields.UE, new org.apache.thrift.meta_data.FieldMetaData("ue", org.apache.thrift.TFieldRequirementType.DEFAULT,
                                                                                 new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRUCT)));
            tmpMap.put(_Fields.SE, new org.apache.thrift.meta_data.FieldMetaData("se", org.apache.thrift.TFieldRequirementType.DEFAULT,
                                                                                 new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRUCT)));
            metaDataMap = Collections.unmodifiableMap(tmpMap);
            org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(publish_result.class, metaDataMap);
        }

        public publish_result() {
        }

        public publish_result(
                org.wso2.carbon.agent.commons.thrift.exception.ThriftUndefinedEventTypeException ue,
                org.wso2.carbon.agent.commons.thrift.exception.ThriftSessionExpiredException se)
        {
            this();
            this.ue = ue;
            this.se = se;
        }

        /**
         * Performs a deep copy on <i>other</i>.
         */
        public publish_result(publish_result other) {
            if (other.isSetUe()) {
                this.ue = new org.wso2.carbon.agent.commons.thrift.exception.ThriftUndefinedEventTypeException(other.ue);
            }
            if (other.isSetSe()) {
                this.se = new org.wso2.carbon.agent.commons.thrift.exception.ThriftSessionExpiredException(other.se);
            }
        }

        public publish_result deepCopy() {
            return new publish_result(this);
        }

        @Override
        public void clear() {
            this.ue = null;
            this.se = null;
        }

        public org.wso2.carbon.agent.commons.thrift.exception.ThriftUndefinedEventTypeException getUe() {
            return this.ue;
        }

        public publish_result setUe(org.wso2.carbon.agent.commons.thrift.exception.ThriftUndefinedEventTypeException ue) {
            this.ue = ue;
            return this;
        }

        public void unsetUe() {
            this.ue = null;
        }

        /** Returns true if field ue is set (has been assigned a value) and false otherwise */
        public boolean isSetUe() {
            return this.ue != null;
        }

        public void setUeIsSet(boolean value) {
            if (!value) {
                this.ue = null;
            }
        }

        public org.wso2.carbon.agent.commons.thrift.exception.ThriftSessionExpiredException getSe() {
            return this.se;
        }

        public publish_result setSe(org.wso2.carbon.agent.commons.thrift.exception.ThriftSessionExpiredException se) {
            this.se = se;
            return this;
        }

        public void unsetSe() {
            this.se = null;
        }

        /** Returns true if field se is set (has been assigned a value) and false otherwise */
        public boolean isSetSe() {
            return this.se != null;
        }

        public void setSeIsSet(boolean value) {
            if (!value) {
                this.se = null;
            }
        }

        public void setFieldValue(_Fields field, Object value) {
            switch (field) {
                case UE:
                    if (value == null) {
                        unsetUe();
                    } else {
                        setUe((org.wso2.carbon.agent.commons.thrift.exception.ThriftUndefinedEventTypeException)value);
                    }
                    break;

                case SE:
                    if (value == null) {
                        unsetSe();
                    } else {
                        setSe((org.wso2.carbon.agent.commons.thrift.exception.ThriftSessionExpiredException)value);
                    }
                    break;

            }
        }

        public Object getFieldValue(_Fields field) {
            switch (field) {
                case UE:
                    return getUe();

                case SE:
                    return getSe();

            }
            throw new IllegalStateException();
        }

        /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
        public boolean isSet(_Fields field) {
            if (field == null) {
                throw new IllegalArgumentException();
            }

            switch (field) {
                case UE:
                    return isSetUe();
                case SE:
                    return isSetSe();
            }
            throw new IllegalStateException();
        }

        @Override
        public boolean equals(Object that) {
            if (that == null)
                return false;
            if (that instanceof publish_result)
                return this.equals((publish_result)that);
            return false;
        }

        public boolean equals(publish_result that) {
            if (that == null)
                return false;

            boolean this_present_ue = true && this.isSetUe();
            boolean that_present_ue = true && that.isSetUe();
            if (this_present_ue || that_present_ue) {
                if (!(this_present_ue && that_present_ue))
                    return false;
                if (!this.ue.equals(that.ue))
                    return false;
            }

            boolean this_present_se = true && this.isSetSe();
            boolean that_present_se = true && that.isSetSe();
            if (this_present_se || that_present_se) {
                if (!(this_present_se && that_present_se))
                    return false;
                if (!this.se.equals(that.se))
                    return false;
            }

            return true;
        }

        @Override
        public int hashCode() {
            return 0;
        }

        public int compareTo(publish_result other) {
            if (!getClass().equals(other.getClass())) {
                return getClass().getName().compareTo(other.getClass().getName());
            }

            int lastComparison = 0;
            publish_result typedOther = (publish_result)other;

            lastComparison = Boolean.valueOf(isSetUe()).compareTo(typedOther.isSetUe());
            if (lastComparison != 0) {
                return lastComparison;
            }
            if (isSetUe()) {
                lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.ue, typedOther.ue);
                if (lastComparison != 0) {
                    return lastComparison;
                }
            }
            lastComparison = Boolean.valueOf(isSetSe()).compareTo(typedOther.isSetSe());
            if (lastComparison != 0) {
                return lastComparison;
            }
            if (isSetSe()) {
                lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.se, typedOther.se);
                if (lastComparison != 0) {
                    return lastComparison;
                }
            }
            return 0;
        }

        public _Fields fieldForId(int fieldId) {
            return _Fields.findByThriftId(fieldId);
        }

        public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
            schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
        }

        public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
            schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
        }

        @Override
        public String toString() {
            StringBuilder sb = new StringBuilder("publish_result(");
            boolean first = true;

            sb.append("ue:");
            if (this.ue == null) {
                sb.append("null");
            } else {
                sb.append(this.ue);
            }
            first = false;
            if (!first) sb.append(", ");
            sb.append("se:");
            if (this.se == null) {
                sb.append("null");
            } else {
                sb.append(this.se);
            }
            first = false;
            sb.append(")");
            return sb.toString();
        }

        public void validate() throws org.apache.thrift.TException {
            // check for required fields
        }

        private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
            try {
                write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
            } catch (org.apache.thrift.TException te) {
                throw new java.io.IOException(te);
            }
        }

        private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
            try {
                read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
            } catch (org.apache.thrift.TException te) {
                throw new java.io.IOException(te);
            }
        }

        private static class publish_resultStandardSchemeFactory implements SchemeFactory {
            public publish_resultStandardScheme getScheme() {
                return new publish_resultStandardScheme();
            }
        }

        private static class publish_resultStandardScheme extends StandardScheme<publish_result> {

            public void read(org.apache.thrift.protocol.TProtocol iprot, publish_result struct) throws org.apache.thrift.TException {
                org.apache.thrift.protocol.TField schemeField;
                iprot.readStructBegin();
                while (true)
                {
                    schemeField = iprot.readFieldBegin();
                    if (schemeField.type == org.apache.thrift.protocol.TType.STOP) {
                        break;
                    }
                    switch (schemeField.id) {
                        case 1: // UE
                            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
                                struct.ue = new org.wso2.carbon.agent.commons.thrift.exception.ThriftUndefinedEventTypeException();
                                struct.ue.read(iprot);
                                struct.setUeIsSet(true);
                            } else {
                                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                            }
                            break;
                        case 2: // SE
                            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
                                struct.se = new org.wso2.carbon.agent.commons.thrift.exception.ThriftSessionExpiredException();
                                struct.se.read(iprot);
                                struct.setSeIsSet(true);
                            } else {
                                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                            }
                            break;
                        default:
                            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                    }
                    iprot.readFieldEnd();
                }
                iprot.readStructEnd();

                // check for required fields of primitive type, which can't be checked in the validate method
                struct.validate();
            }

            public void write(org.apache.thrift.protocol.TProtocol oprot, publish_result struct) throws org.apache.thrift.TException {
                struct.validate();

                oprot.writeStructBegin(STRUCT_DESC);
                if (struct.ue != null) {
                    oprot.writeFieldBegin(UE_FIELD_DESC);
                    struct.ue.write(oprot);
                    oprot.writeFieldEnd();
                }
                if (struct.se != null) {
                    oprot.writeFieldBegin(SE_FIELD_DESC);
                    struct.se.write(oprot);
                    oprot.writeFieldEnd();
                }
                oprot.writeFieldStop();
                oprot.writeStructEnd();
            }

        }

        private static class publish_resultTupleSchemeFactory implements SchemeFactory {
            public publish_resultTupleScheme getScheme() {
                return new publish_resultTupleScheme();
            }
        }

        private static class publish_resultTupleScheme extends TupleScheme<publish_result> {

            @Override
            public void write(org.apache.thrift.protocol.TProtocol prot, publish_result struct) throws org.apache.thrift.TException {
                TTupleProtocol oprot = (TTupleProtocol) prot;
                BitSet optionals = new BitSet();
                if (struct.isSetUe()) {
                    optionals.set(0);
                }
                if (struct.isSetSe()) {
                    optionals.set(1);
                }
                oprot.writeBitSet(optionals, 2);
                if (struct.isSetUe()) {
                    struct.ue.write(oprot);
                }
                if (struct.isSetSe()) {
                    struct.se.write(oprot);
                }
            }

            @Override
            public void read(org.apache.thrift.protocol.TProtocol prot, publish_result struct) throws org.apache.thrift.TException {
                TTupleProtocol iprot = (TTupleProtocol) prot;
                BitSet incoming = iprot.readBitSet(2);
                if (incoming.get(0)) {
                    struct.ue = new org.wso2.carbon.agent.commons.thrift.exception.ThriftUndefinedEventTypeException();
                    struct.ue.read(iprot);
                    struct.setUeIsSet(true);
                }
                if (incoming.get(1)) {
                    struct.se = new org.wso2.carbon.agent.commons.thrift.exception.ThriftSessionExpiredException();
                    struct.se.read(iprot);
                    struct.setSeIsSet(true);
                }
            }
        }

    }

}
