/**
 * Copyright (c) 2009, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.wso2.carbon.bam.core.configurations;

import java.util.List;

public abstract class AbstractIndexConfiguration implements IndexConfiguration {

    private final String indexName;

    private final IndexType indexType;

    private final String indexedTable;

    private final DataSourceType dataSourceType;

    private String[] indexedColumns;

    private boolean autoGenerated;

    private boolean manuallyIndexed;

    private Granularity granularity;

    public AbstractIndexConfiguration(String indexName, String indexedTable,
                                      String[] indexedColumns, DataSourceType dataSourceType) {
        this.indexName = indexName;

        if (indexedColumns != null && indexedColumns.length > 1) {
            this.indexType = IndexType.COMPOSITE;
        } else {
            this.indexType = IndexType.SINGLE;
        }

        this.indexedTable = indexedTable;
        this.dataSourceType = dataSourceType;
        this.indexedColumns = indexedColumns;

    }

    @Override
    public String getIndexName() {
        return indexName;
    }

    @Override
    public IndexType getIndexType() {
        return indexType;
    }

    @Override
    public String getIndexedTable() {
        return indexedTable;
    }

    @Override
    public String[] getIndexedColumns() {
        return indexedColumns;
    }

    public void setIndexedColumns(String[] indexedColumns) {
        this.indexedColumns = indexedColumns;
    }

    @Override
    public DataSourceType getDataSourceType() {
        return dataSourceType;
    }

    @Override
    public boolean isAutoGenerated() {
        return autoGenerated;
    }

    public void setAutoGenerated(boolean autoGenerated) {
        this.autoGenerated = autoGenerated;
    }

    @Override
    public Granularity getGranularity() {
        return granularity;
    }

    public void setGranularity(Granularity granularity) {
        this.granularity = granularity;
    }

    public boolean isManuallyIndexed() {
        return manuallyIndexed;
    }

    public void setManuallyIndexed(boolean manuallyIndexed) {
        this.manuallyIndexed = manuallyIndexed;
    }

}
