-- WSO2 METERING DATABASE SQL FOR MySQL

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";

SET AUTOCOMMIT=0;
START TRANSACTION;

--
-- TABLES
--

CREATE TABLE IF NOT EXISTS BAM_BANDWIDTH_STAT_HOUR_FACT (
  BAM_ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  BAM_SERVER_ID INT(10) UNSIGNED NOT NULL,
  BAM_HOUR_ID INT(10) UNSIGNED NOT NULL,
  BAM_BANDWIDTH_NAME VARCHAR(512) NOT NULL,
  BAM_INCOMING_BANDWIDTH_GB INT(20) NOT NULL,
  BAM_INCOMING_BANDWIDTH_MB INT(20) NOT NULL,
  BAM_INCOMING_BANDWIDTH_KB INT(20) NOT NULL,
  BAM_INCOMING_BANDWIDTH_B INT(20) NOT NULL,
  BAM_OUTGOING_BANDWIDTH_GB INT(20) NOT NULL,
  BAM_OUTGOING_BANDWIDTH_MB INT(20) NOT NULL,
  BAM_OUTGOING_BANDWIDTH_KB INT(20) NOT NULL,
  BAM_OUTGOING_BANDWIDTH_B INT(20) NOT NULL,
  PRIMARY KEY (BAM_ID),
  KEY BAM_SERVER_ID (BAM_SERVER_ID),
  KEY BAM_HOUR_ID (BAM_HOUR_ID)
) ENGINE=INNODB  DEFAULT CHARSET=LATIN1 AUTO_INCREMENT=1 ;

 

CREATE TABLE IF NOT EXISTS BAM_BANDWIDTH_STAT_DAY_FACT (
  BAM_ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  BAM_SERVER_ID INT(10) UNSIGNED NOT NULL,
  BAM_DAY_ID INT(10) UNSIGNED NOT NULL,
  BAM_BANDWIDTH_NAME VARCHAR(512) NOT NULL,
  BAM_INCOMING_BANDWIDTH_GB INT(20) NOT NULL,
  BAM_INCOMING_BANDWIDTH_MB INT(20) NOT NULL,
  BAM_INCOMING_BANDWIDTH_KB INT(20) NOT NULL,
  BAM_INCOMING_BANDWIDTH_B INT(20) NOT NULL,
  BAM_OUTGOING_BANDWIDTH_GB INT(20) NOT NULL,
  BAM_OUTGOING_BANDWIDTH_MB INT(20) NOT NULL,
  BAM_OUTGOING_BANDWIDTH_KB INT(20) NOT NULL,
  BAM_OUTGOING_BANDWIDTH_B INT(20) NOT NULL,
  PRIMARY KEY (BAM_ID),
  KEY BAM_SERVER_ID (BAM_SERVER_ID),
  KEY BAM_DAY_ID (BAM_DAY_ID)
) ENGINE=INNODB  DEFAULT CHARSET=LATIN1 AUTO_INCREMENT=1 ;

 

CREATE TABLE IF NOT EXISTS BAM_BANDWIDTH_STAT_MONTH_FACT (
  BAM_ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  BAM_SERVER_ID INT(10) UNSIGNED NOT NULL,
  BAM_MONTH_ID INT(10) UNSIGNED NOT NULL,
  BAM_BANDWIDTH_NAME VARCHAR(512) NOT NULL,
  BAM_INCOMING_BANDWIDTH_GB INT(20) NOT NULL,
  BAM_INCOMING_BANDWIDTH_MB INT(20) NOT NULL,
  BAM_INCOMING_BANDWIDTH_KB INT(20) NOT NULL,
  BAM_INCOMING_BANDWIDTH_B INT(20) NOT NULL,
  BAM_OUTGOING_BANDWIDTH_GB INT(20) NOT NULL,
  BAM_OUTGOING_BANDWIDTH_MB INT(20) NOT NULL,
  BAM_OUTGOING_BANDWIDTH_KB INT(20) NOT NULL,
  BAM_OUTGOING_BANDWIDTH_B INT(20) NOT NULL,
  PRIMARY KEY (BAM_ID),
  KEY BAM_SERVER_ID (BAM_SERVER_ID),
  KEY BAM_MONTH_ID (BAM_MONTH_ID)
) ENGINE=INNODB  DEFAULT CHARSET=LATIN1 AUTO_INCREMENT=1 ;

  

CREATE TABLE IF NOT EXISTS BAM_BANDWIDTH_STAT_QTR_FACT (
  BAM_ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  BAM_SERVER_ID INT(10) UNSIGNED NOT NULL,
  BAM_QTR_ID INT(10) UNSIGNED NOT NULL,
  BAM_BANDWIDTH_NAME VARCHAR(512) NOT NULL,
  BAM_INCOMING_BANDWIDTH_GB INT(20) NOT NULL,
  BAM_INCOMING_BANDWIDTH_MB INT(20) NOT NULL,
  BAM_INCOMING_BANDWIDTH_KB INT(20) NOT NULL,
  BAM_INCOMING_BANDWIDTH_B INT(20) NOT NULL,
  BAM_OUTGOING_BANDWIDTH_GB INT(20) NOT NULL,
  BAM_OUTGOING_BANDWIDTH_MB INT(20) NOT NULL,
  BAM_OUTGOING_BANDWIDTH_KB INT(20) NOT NULL,
  BAM_OUTGOING_BANDWIDTH_B INT(20) NOT NULL,
  PRIMARY KEY (BAM_ID),
  KEY BAM_SERVER_ID (BAM_SERVER_ID),
  KEY BAM_QTR_ID (BAM_QTR_ID)
) ENGINE=INNODB  DEFAULT CHARSET=LATIN1 AUTO_INCREMENT=1 ;

 

CREATE TABLE IF NOT EXISTS BAM_BANDWIDTH_STAT_YEAR_FACT (
  BAM_ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  BAM_SERVER_ID INT(10) UNSIGNED NOT NULL,
  BAM_YEAR_ID INT(10) UNSIGNED NOT NULL,
  BAM_BANDWIDTH_NAME VARCHAR(512) NOT NULL,
  BAM_INCOMING_BANDWIDTH_GB INT(20) NOT NULL,
  BAM_INCOMING_BANDWIDTH_MB INT(20) NOT NULL,
  BAM_INCOMING_BANDWIDTH_KB INT(20) NOT NULL,
  BAM_INCOMING_BANDWIDTH_B INT(20) NOT NULL,
  BAM_OUTGOING_BANDWIDTH_GB INT(20) NOT NULL,
  BAM_OUTGOING_BANDWIDTH_MB INT(20) NOT NULL,
  BAM_OUTGOING_BANDWIDTH_KB INT(20) NOT NULL,
  BAM_OUTGOING_BANDWIDTH_B INT(20) NOT NULL,
  PRIMARY KEY (BAM_ID),
  KEY BAM_SERVER_ID (BAM_SERVER_ID),
  KEY BAM_YEAR_ID (BAM_YEAR_ID)
) ENGINE=INNODB  DEFAULT CHARSET=LATIN1 AUTO_INCREMENT=1 ;

  

CREATE TABLE IF NOT EXISTS BAM_REG_BANDWIDTH_USAGE_DAY_FACT (
  BAM_ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  BAM_TENANT_ID INT(10) UNSIGNED NOT NULL,
  BAM_DAY_ID INT(10) UNSIGNED NOT NULL,
  BAM_BANDWIDTH_NAME VARCHAR(512) NOT NULL,
  BAM_REG_BANDWIDTH_GB INT(20) NOT NULL,
  BAM_REG_BANDWIDTH_MB INT(20) NOT NULL,
  BAM_REG_BANDWIDTH_KB INT(20) NOT NULL,
  BAM_REG_BANDWIDTH_B INT(20) NOT NULL,
  BAM_REG_HISTORY_BANDWIDTH_GB INT(20) NOT NULL,
  BAM_REG_HISTORY_BANDWIDTH_MB INT(20) NOT NULL,
  BAM_REG_HISTORY_BANDWIDTH_KB INT(20) NOT NULL,
  BAM_REG_HISTORY_BANDWIDTH_B INT(20) NOT NULL,
  PRIMARY KEY (BAM_ID),
  KEY BAM_DAY_ID (BAM_DAY_ID)
) ENGINE=INNODB  DEFAULT CHARSET=LATIN1 AUTO_INCREMENT=1 ;

 

CREATE TABLE IF NOT EXISTS BAM_REG_BANDWIDTH_USAGE_MONTH_FACT (
  BAM_ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  BAM_TENANT_ID INT(10) UNSIGNED NOT NULL,
  BAM_MONTH_ID INT(10) UNSIGNED NOT NULL,
  BAM_BANDWIDTH_NAME VARCHAR(512) NOT NULL,
  BAM_REG_BANDWIDTH_GB INT(20) NOT NULL,
  BAM_REG_BANDWIDTH_MB INT(20) NOT NULL,
  BAM_REG_BANDWIDTH_KB INT(20) NOT NULL,
  BAM_REG_BANDWIDTH_B INT(20) NOT NULL,
  BAM_REG_HISTORY_BANDWIDTH_GB INT(20) NOT NULL,
  BAM_REG_HISTORY_BANDWIDTH_MB INT(20) NOT NULL,
  BAM_REG_HISTORY_BANDWIDTH_KB INT(20) NOT NULL,
  BAM_REG_HISTORY_BANDWIDTH_B INT(20) NOT NULL,
  PRIMARY KEY (BAM_ID),
  KEY BAM_MONTH_ID (BAM_MONTH_ID)
) ENGINE=INNODB  DEFAULT CHARSET=LATIN1 AUTO_INCREMENT=1 ;



CREATE TABLE  IF NOT EXISTS BAM_INSTANCE_USAGE (
  START_TIMESTAMP timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '''0000-00-00 00:00:00''',
  INSTANCE_ID int(10) unsigned zerofill NOT NULL AUTO_INCREMENT,
  STOP_TIMESTAMP timestamp NOT NULL DEFAULT '2001-01-01 00:00:00',
  IS_RUNNING tinyint(1) DEFAULT '0',
  SERVER_URL varchar(40) DEFAULT NULL,
  SERVER_NAME varchar(40) DEFAULT NULL,
  PRIMARY KEY (`INSTANCE_ID`)
) ENGINE=MyISAM AUTO_INCREMENT=228 DEFAULT CHARSET=latin1 COMMENT='Stores Inastance usages of the server that running';



-- 
-- CONSTRAINTS
--


ALTER TABLE BAM_BANDWIDTH_STAT_HOUR_FACT
  ADD CONSTRAINT BAM_BANDWIDTH_STAT_HOUR_FACT_IBFK_2 FOREIGN KEY (BAM_HOUR_ID) REFERENCES BAM_HOUR_DIM (BAM_ID),
  ADD CONSTRAINT BAM_BANDWIDTH_STAT_HOUR_FACT_IBFK_1 FOREIGN KEY (BAM_SERVER_ID) REFERENCES BAM_SERVER (BAM_SERVER_ID);



ALTER TABLE BAM_BANDWIDTH_STAT_DAY_FACT
  ADD CONSTRAINT BAM_BANDWIDTH_STAT_DAY_FACT_IBFK_2 FOREIGN KEY (BAM_DAY_ID) REFERENCES BAM_DAY_DIM (BAM_ID),
  ADD CONSTRAINT BAM_BANDWIDTH_STAT_DAY_FACT_IBFK_1 FOREIGN KEY (BAM_SERVER_ID) REFERENCES BAM_SERVER (BAM_SERVER_ID);

 

ALTER TABLE BAM_BANDWIDTH_STAT_MONTH_FACT
  ADD CONSTRAINT BAM_BANDWIDTH_STAT_MONTH_FACT_IBFK_2 FOREIGN KEY (BAM_MONTH_ID) REFERENCES BAM_MONTH_DIM (BAM_ID),
  ADD CONSTRAINT BAM_BANDWIDTH_STAT_MONTH_FACT_IBFK_1 FOREIGN KEY (BAM_SERVER_ID) REFERENCES BAM_SERVER (BAM_SERVER_ID);

 

ALTER TABLE BAM_BANDWIDTH_STAT_QTR_FACT
  ADD CONSTRAINT BAM_BANDWIDTH_STAT_QTR_FACT_IBFK_2 FOREIGN KEY (BAM_QTR_ID) REFERENCES BAM_QTR_DIM (BAM_ID),
  ADD CONSTRAINT BAM_BANDWIDTH_STAT_QTR_FACT_IBFK_1 FOREIGN KEY (BAM_SERVER_ID) REFERENCES BAM_SERVER (BAM_SERVER_ID);  

 

ALTER TABLE BAM_BANDWIDTH_STAT_YEAR_FACT
  ADD CONSTRAINT BAM_BANDWIDTH_STAT_YEAR_FACT_IBFK_2 FOREIGN KEY (BAM_YEAR_ID) REFERENCES BAM_YEAR_DIM (BAM_ID),
  ADD CONSTRAINT BAM_BANDWIDTH_STAT_YEAR_FACT_IBFK_1 FOREIGN KEY (BAM_SERVER_ID) REFERENCES BAM_SERVER (BAM_SERVER_ID);  

  

ALTER TABLE BAM_REG_BANDWIDTH_USAGE_DAY_FACT
  ADD CONSTRAINT BAM_REG_BANDWIDTH_USAGE_DAY_FACT_IBFK_1 FOREIGN KEY (BAM_DAY_ID) REFERENCES BAM_DAY_DIM (BAM_ID);  
  

ALTER TABLE BAM_REG_BANDWIDTH_USAGE_MONTH_FACT
  ADD CONSTRAINT BAM_REG_BANDWIDTH_USAGE_MONTH_FACT_IBFK_1 FOREIGN KEY (BAM_MONTH_ID) REFERENCES BAM_MONTH_DIM (BAM_ID);



COMMIT;

